### ISSUE TITLE
Plugins should include their build version

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#101]
Not knowing the exact plugin version makes debugging tricky, especially when it's not clear where the cni binaries come from.

The plugins should have some kind of a `--version` argument or equivalent.

**Comment by lsm5** [comment]
atm, `git describe` on master branch tells me `v0.7.2-123-gb93d284` while there's already a v0.7.3 release. Not sure that's consistent.

**Comment by lsm5** [comment]
@dcbw  ping ^
