### ISSUE TITLE
plugin version unknown (1.4.1 release)

### ISSUE THREAD

**Issue by tristanmorgan** [containernetworking/plugins#1019]
Hi, The latest builds (1.4.1) of the CNI plugins are not printing the plugin versions when run.
I've tested both x86_64 and Arm64 packages. I suspect changes in the build process since 1.4.0 release missed setting `BuildVersion`.
 
```bash
# /opt/cni/bin/dummy 
CNI dummy plugin version unknown
CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0
```

**Comment by maxadamo** [comment]
This is going to create problems to other tools, for instance mine: https://github.com/GEANT/nomad_cni/blob/main/lib/facter/nomad_cni_version.rb

May I suggest to delete and reissue this version?

**Comment by FibreFoX** [comment]
Or just release 1.4.2 instead of re-publishing, maybe to address #1033 too

**Comment by antoninbas** [comment]
+1
This script is no longer used for releases: https://github.com/containernetworking/plugins/blob/main/scripts/release.sh
As a result, `github.com/containernetworking/plugins/pkg/utils/buildversion.BuildVersion` is no longer set using linker flags.

**Comment by squeed** [comment]
@s1061123 can you take a look? I know you worked on automated release building.

**Comment by squeed** [comment]
In the mean time, I'll re-build the release with the version set properly.

**Comment by squeed** [comment]
Rebuilt the release, PTA>

**Comment by s1061123** [comment]
@squeed I got that script misses build version (ldflags in release.sh script). Will fix that soon.

**Comment by s1061123** [comment]
@squeed https://github.com/containernetworking/plugins/pull/1037 fixes the issue. PTAL?
