### ISSUE TITLE
v1.4.1 binaries were modified?

### ISSUE THREAD

**Issue by AkihiroSuda** [containernetworking/plugins#1038]
https://github.com/containernetworking/plugins/releases/tag/v1.4.1

The v1.4.1 binaries seems modified without any announcement today.
Was this conducted by a maintainer? Are new binaries trustworthy?

**Comment by AkihiroSuda** [comment]
Thanks for quick explanation.
Next time could you consider keeping the binaries immutable, and just make a new release?

**Comment by medyagh** [comment]
I agree, this broke our ISO build process since the SHAs were changed and it was seens as a not genuine binary
