### ISSUE TITLE
Windows binaries missing from release assets for v1.5.1

### ISSUE THREAD

**Issue by antoninbas** [containernetworking/plugins#1059]
The most recent release (v1.5.1) is missing Windows binaries in assets

<img width="950" alt="image" src="https://github.com/containernetworking/plugins/assets/2495809/15d79bea-598f-49d4-a482-790ae3508de4">

The reason is that the workflow responsible for uploading Windows binaries as assets failed: https://github.com/containernetworking/plugins/actions/runs/9550729510/job/26323387759

It looks like it could be a transient error rather than an issue with the Github workflow definition, so maybe triggering a new run of this workflow will resolve the issue.

**Comment by antoninbas** [comment]
cc @squeed @s1061123

**Comment by squeed** [comment]
Even sillier than that, I suspect I just created the release too soon. Argh, sorry about that.

**Comment by squeed** [comment]
@antoninbas I just needed to re-trigger the release CI and it updated everything. This should be fixed.

**Comment by antoninbas** [comment]
Thanks @squeed
