### ISSUE TITLE
Flaky SBR tests due to routes with link-local IP

### ISSUE THREAD

**Issue by LionelJouin** [containernetworking/plugins#1096]
Here is an example of fail test run: https://github.com/containernetworking/plugins/actions/runs/10952855591/job/30412240836?pr=1092

This is due to a route with the link-local IP being automatically added after the test run saves the initial state (routes before SBR plugin is ran). When the SBR plugin is ran, the new state is compared with the old state. The new state will then contain the route with the link-local IP (that has been added after saving the old state), the old state was not containing it, so the tests were failing

A solution would be to ignore routes with the link-local IP for the tests, or to somehow wait for the routes with the link-local IP to be created.

**Comment by squeed** [comment]
We talked about this at the meeting; we will just ignore link-local routes in the tests.

the issue, unsurprisingly, is ipv6 DAD.
