### ISSUE TITLE
cni-plugins v1.6.1 s390x binaries are missing

### ISSUE THREAD

**Issue by saschagrunert** [containernetworking/plugins#1126]
Hey folks, the latest release is duplicated on the releases page and is also missing the s390x binaries: https://github.com/containernetworking/plugins/releases

**Comment by s1061123** [comment]
Thank you for the info. Rerun release job and now it has the one.

**Comment by s1061123** [comment]
I don't know about duplicated release, but it is not a blocker, I guess.
As far as I checked, both point same commit, so it should be okay.

Could you check plugins in the latest release? If no update, I will close this issue.

**Comment by saschagrunert** [comment]
I think we should be fine for now.
