### ISSUE TITLE
Unable to add custom DNS to container using flannel plugin 

### ISSUE THREAD

**Issue by suryakantgarg** [containernetworking/plugins#128]
My /etc/cni/net.d/10-flannelnet.conf file looks like this :
{
  "name": "flannelnet",
  "type": "flannel",
  "subnetFile": "/var/run/flannel/subnet.env",
   "delegate":{ "isDefaultGateway": true},
  "dns": {
    "nameservers": [ "10.112.10.2" ]
  }
}

I tried to create network endpoint using scripts avaliable at : https://github.com/containernetworking/cni/tree/master/scripts

Endpoint inside container gets created but there is no entry of dns server in /etc/resolv.conf inside container

**Comment by squeed** [comment]
The DNS field in CNI is currently unused by most runtimes, rkt being the only exception. So if you're using Kubernetes, for example, it won't work.

It should probably just be removed.

**Comment by rosenhouse** [comment]
Cloud Foundry respects it too! :-)
