### ISSUE TITLE
ptp plugin + IPVS hairpin issue

### ISSUE THREAD

**Issue by m1093782566** [containernetworking/plugins#139]
My test:

* The CNI config file looks like,

```
{
        "name": "mynet",
        "type": "ptp",
        "ipMasq": true,
        "ipam": {
                "type": "host-local",
                "subnet": "10.1.1.0/24",
                "routes": [
                        { "dst": "0.0.0.0/0" }
                ]
        }
}
```

* Run a container(nginx) with ptp plugin,

```
./docker-run.sh -it --rm docker.io/richarvey/nginx-php-fpm
```

* Enter the running container and curl its IP + Port, it's reachable.

* Enter the running container and curl a VIP(its real backend is the container itself) + Port, it's unreachable. 
PS. I created an IPVS virtual server.
```
[root@SHA1000130405 ~]# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  1.2.3.4:80 rr
  -> 10.1.1.16:80                 Route   1      0          0
```
and bound the VIP(1.2.3.4) to a local dummy device.

```
551: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN
    link/ether 5a:e7:c7:95:e0:82 brd ff:ff:ff:ff:ff:ff
    inet 1.2.3.4/32 scope global kube-ipvs0
```

@squeed

**Comment by m1093782566** [comment]
I also have tried to create an iptables MASQ rule for the traffic visiting the VIP, but does not work.

**Comment by jingax10** [comment]
> I also have tried to create an iptables MASQ rule for the traffic(masquerade all), but still does not work.

What is your Masquerade rule? What have you seen from tcpdump?

I tried in K8s env, PTP plugin works in the scenario you described (It did not work for me as I have some pending PR in my client).

**Comment by m1093782566** [comment]
@jingax10 

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
KUBE-POSTROUTING  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */

Chain KUBE-MARK-MASQ (1 references)
target     prot opt source               destination
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK or 0x4000

Chain KUBE-POSTROUTING (1 references)
target     prot opt source               destination
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000

Chain KUBE-SERVICES (2 references)
target     prot opt source               destination
KUBE-MARK-MASQ  all  --  0.0.0.0/0            0.0.0.0/0
```

**Comment by m1093782566** [comment]
When I tried to use iptables doing DNAT, the hairpin issue is resolved. 

So, I am wondering if ptp can work with IPVS......

**Comment by squeed** [comment]
thanks for the reproduction steps! I'll try and take a look at this in the next few days too. I'm not super familiar with ipvs, so any help is appreciated.

**Comment by lbernail** [comment]
I just tried PTP with kube-proxy in IPVS mode and it seems to be working

My setup is the following:
- containerd runtime (kubelet started with ```--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock```
- containerd ptp template:
    containerd.toml with: ```conf_template = "/etc/cni/template.conflist"```
    template.conflist:
```
{
  "name": "k8s-pod-network",
    "cniVersion": "0.3.1",
    "plugins": [
      {
        "type": "ptp",
        "mtu": 1460,
        "ipam": {
          "type": "host-local",
          "subnet": "{{.PodCIDR}}",
          "routes": [
            {
              "dst": "0.0.0.0/0"
            }
          ]
        }
      }
    ]
}
```
- kube-proxy in IPVS mode (```--proxy-mode=ipvs```)

I create a service backed with a deployment running a local and remote pods and if I enter the network namespace of a pod and access the service, I can access remote and local pods:
```shell
$ sudo ip netns exec cni-68933685-4e35-d548-9b70-a1f90c626c8f bash
# ip addr show dev eth0
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default
    link/ether ee:fe:90:89:78:10 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.150.6.3/24 scope global eth0
       valid_lft forever preferred_lft forever

while true ; do curl 10.200.121.127 ; sleep 1 ; done
Container: 10.150.7.4      | Source: 10.150.6.3      | Version: v2
Container: 10.150.7.3      | Source: 10.150.6.3      | Version: v2
Container: 10.150.6.3      | Source: 10.150.6.1      | Version: v2
Container: 10.150.6.2      | Source: 10.150.6.3      | Version: v2
Container: 10.150.4.4      | Source: 10.150.6.3      | Version: v2
```
Where ```10.200.121.127``` is the ClusterIP of a service simply echoing the pod IP address and the source of the query. We can see both remote pods and the local ones. The only difference for hairpin traffic is that the source IP is SNATed on the host (```Source: 10.150.6.1```)

**Comment by lbernail** [comment]
After digging into it, this is solved by masquerading hairpin traffic:
```
-A KUBE-POSTROUTING -m set --match-set KUBE-LOOP-BACK dst,dst,src -j MASQUERADE
```
with the ipset ```KUBE-LOOP-BACK```  matching all hairpin communication:
```
ipset -L KUBE-LOOP-BACK
Name: KUBE-LOOP-BACK
Type: hash:ip,port,ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 1056
References: 1
Number of entries: 13
Members:
10.150.6.2,tcp:5000,10.150.6.2
10.150.6.3,tcp:5000,10.150.6.3
10.150.7.4,tcp:5000,10.150.7.4
10.150.4.4,tcp:5000,10.150.4.4
10.150.7.3,tcp:5000,10.150.7.3
```

**Comment by squeed** [comment]
That's what I expected, thanks for finding that! Crafting the right rules for hairpin DNAT is complicated. We need 3 cases:

1. src == dest
2. src is in PodCIDR
3. it has been routed.

This is a bit crazy, but I think we can do it with:

`- A KUBE-POSTROUTING -m bpf --bytecode "$(nfbpf_compile RAW 'ip and ip[12:4] == ip[16:4] and src net ${PODCIDR}')"`

**Comment by lbernail** [comment]
@squeed not sure I follow: it is already working (in the setup I described at least) because the ipvs proxier is creating the proper ipset to match hairpin traffic and iptables rule to SNAT it

**Comment by squeed** [comment]
Aha, excellent!
