### ISSUE TITLE
Regression in v0.7.0 bridge plugin

### ISSUE THREAD

**Issue by jellonek** [containernetworking/plugins#140]
a124fb36e668aecd917d92aa7965a8332b3d5f74 seems to be the moment starting from which bridge plugin stopped reporting mac address of container interface, what was probably handled up to this change in https://github.com/containernetworking/plugins/commit/a124fb36e668aecd917d92aa7965a8332b3d5f74#diff-b4fc1e43896318cdf10ecd779954aeeaL390 line.

**Comment by squeed** [comment]
Ah yes. I'll release 0.7.1 with a fix shortly.

**Comment by squeed** [comment]
Filed #141 - will do a 0.7.1 release then merge in to master.

**Comment by squeed** [comment]
And v0.7.1 is released!

**Comment by jellonek** [comment]
Thx!
