### ISSUE TITLE
include version number somewhere in the source

### ISSUE THREAD

**Issue by lsm5** [containernetworking/plugins#142]
I'm looking to do automated rpm builds of master branch of this repo for the `containernetworking-cni` rpm on Fedora rawhide. Part of it involves grabbing the latest version number. But, afaict, version number is recorded only in git tags which won't quite work for me since I'll be using master. So, I'm hoping you can have the string mentioned in the source somewhere.

/cc @fkluknav

**Comment by lsm5** [comment]
@squeed @dcbw PTAL ^

**Comment by dlipovetsky** [comment]
This looks like an implementation detail of #101

**Comment by lsm5** [comment]
closing in favour of #101
