### ISSUE TITLE
Re-using of IP address of terminated PODS

### ISSUE THREAD

**Issue by subrnath** [containernetworking/plugins#146]
If the POD is terminated, IP address of the terminated POD doesn't get re-allocated to a new POD, deployed with a different docker image than the terminated POD. If the new POD is deployed with the same Docker image, IP address of the terminated POD is re-allocated.

Workaround of the problem - once the POD is terminated, delete the /var/lib/cni/networks/.

This issue is redirected from multus forum - https://github.com/Intel-Corp/multus-cni/issues/54.

**Comment by jellonek** [comment]
That do you mean by "POD is terminated"? You are speaking about kubernetes pod?
Was this pod garbage collected by kubelet? Do this GC went without any error?
If there was no error during DEL command - `host-local` should release IP and it should be again reusable.
Can you describe the issue in more details, how to reproduce it?

**Comment by subrnath** [comment]
Yes. It's kubernetes POD.

Reproduction Step-
1. Define K8S CustomResourceDefinition for Network object. Here is the definition of the network object. 
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: <name>
plugin: ipvlan
args: '[
                {
                "name": "<name>",
                "type": "ipvlan",
                "master": "<interface name>",
                "ipam": {
                        "type": "host-local",
                        "subnet": "169.254.32.0/24",
                        "rangeStart": "169.254.32.112",
                        "rangeEnd": "169.254.32.112"
                }
        }

Note: we are defining a single IP in the start and end, so that POD is assigned the expected IP address.

2. Deploy a POD with this network definition in the  deployment file 

  template:
    metadata:
      annotations:
        networks: '[
{ "name": "<name of the network>" }
        ]'

3. Deployment is fine. POD is up with the expected IP.
4.last_reserved_ip.0 is created under /var/lib/cni/networks/<name of the network>.
5. Delete the POD.
6. Files created under  /var/lib/cni/networks/<name of the network> is not cleaned during POD termination.
7.Create a new POD with a different image but with the same network name  as mentioned in the step 2.
8. Issue will be seen now during the deployment of the new POD where journalctl shows the error like no free IP found. 

Note: As we have put single IP in the start and end, issue will be seen in second deployment. But if there is more than one IPs in the range, same issue will be seen in the subsequent deployment.

**Comment by rkamudhan** [comment]
@subrnath Can we use the following project to clean up the network IP address ?? https://github.com/swiftmedical/cni-cleanup

**Comment by rkamudhan** [comment]
@dcbw is there any solution available within the CNI to clean unused IP address ?

**Comment by subrnath** [comment]
@rkamudhan 

Documentation is not clear in https://github.com/swiftmedical/cni-cleanup. How to invoke the command? Do we need to integrate it with Deployment file? I don't see this "/var/lib/cni/networks/podnet" as well.

**Comment by subrnath** [comment]
Is there any update on this? We got another random issue related to cni cleanup where after POD termination, "Journalctl" shows the following error message - 
unregister_netdevice: waiting for eth1 to become free. Usage count = 1

please note, in VNF we are renaming the interfaces created by cni from net0 to eth1. 

This problem is quite severe that, once this issue is hit, no further POD deployment goes through and we need to reset the server to recover.

**Comment by squeed** [comment]
What you're mentioning is a docker race condition triggering a kernel race condition. There is nothing CNI can do.

As for IP reuse, CNI will of course not let you reuse an IP until you delete it. If you want multiple containers using the same IP, then you will need to write an IP allocator that does not do locking. Your containers won't work and your users will hate you, but you can re-use an IP already in use.
