### ISSUE TITLE
Kubernetes pod's hostIP does not function 

### ISSUE THREAD

**Issue by wouterhund** [containernetworking/plugins#149]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When specifying `hostIP: $IP` for a pod, the resulting IP tables rule does not contain `-d $IP` as expected.

**What you expected to happen**:

That the generated iptables rule has `-d $IP` alongside `--dport $PORT`

**How to reproduce it (as minimally and precisely as possible)**:

Create a deployment: `kubectl run my-nginx --image=nginx --port=80`

Use `kubectl edit deployment my-nginx` to set

        ports:
        - containerPort: 80
          hostIP: 192.168.1.101
          hostPort: 18080
          protocol: TCP

Check with `iptables -t nat -S` and see:

    -A CNI-DN-80ae20ae0de6904d5f4b4 -p tcp -m tcp --dport 18080 -j DNAT --to-destination 10.233.64.15:80

There is no `-d 192.168.1.101` as I would expect.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.5
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): 4.4.0-116-generic
- Install tools: Kubespray
- Others: Tested with both Flannel and Calico networking

Taken from https://github.com/kubernetes/kubernetes/issues/62112#issuecomment-382201895

**Comment by squeed** [comment]
Interesting. From the code, it looks like it should work, and I see that the kubelet is passing the correct arguments. Can you test manually using `cnitool` and faking the runtime config manually?

**Comment by squeed** [comment]
Nevermind, it's a kubernetes bug. Updated the k8s issue.
