### ISSUE TITLE
Simplify pod routing for PTP plugin

### ISSUE THREAD

**Issue by lbernail** [containernetworking/plugins#150]
The pod routing configuration when using the PTP plugin is a bit complicated.
From the code:

> 	// The IPAM result will be something like IP=192.168.3.5/24, GW=192.168.3.1.
	// What we want is really a point-to-point link but veth does not support IFF_POINTTOPOINT.
	// Next best thing would be to let it ARP but set interface to 192.168.3.5/32 and
	// add a route like "192.168.3.0/24 via 192.168.3.1 dev $ifName".
	// Unfortunately that won't work as the GW will be outside the interface's subnet.
	// Our solution is to configure the interface with 192.168.3.5/24, then delete the
	// "192.168.3.0/24 dev $ifName" route that was automatically added. Then we add
	// "192.168.3.1/32 dev $ifName" and "192.168.3.0/24 via 192.168.3.1 dev $ifName".
	// In other words we force all traffic to ARP via the gateway except for GW itself.

A simpler solution would be to use a /32 address on the interface and add a ```scope link``` route to the gateway.

Here is an example of how it could work in the pod:
```
ip addr add 10.150.1.2/32 dev eth0
ip route add 10.150.1.1 scope link dev eth0
ip route add default via 10.150.1.1
```

In addition, the veth interface on the host does not require an IP address, we could reuse the IP address from the main interface. Let's consider a host with main IP address 10.1.208.5:
In the pod:
```
ip addr add 10.150.1.2/32 dev eth0
ip route add 10.1.208.5 scope link dev eth0
ip route add default via 10.1.208.5
```

On the host:
```
ip route add 10.150.1.2 scope link dev veth3ea6f687
```
Without the need for an IP address on interface veth3ea6f687
This setup may be slightly more complicated because it requires identifying the main IP address but we could also alias 10.150.1.1/32 on the primary interface

**Comment by lbernail** [comment]
After looking at current PRs, this is very close to #137 
(the only difference is to use an explicit IP address instead of a static ARP entry with ARP proxying)

**Comment by squeed** [comment]
This is pretty cool, though I think that people tend to be attached to classical idea of a "gateway ip," especially in circumstances where the node's IP could change (e.g. a DHCP host).

In any case, the question is this: should the container interface still "pretend" to have the netmask provided to it from the IPAM plugin? Obviously that netmask is a bit fake, since we delete the route this creates. I don't know of anything that relies on knowing it's in a "/24", but there might be.

**Comment by lbernail** [comment]
If we want a gateway IP we can still alias it to a physical interface or create a dummy interface on the host with this IP (this would be similar to static ARP entry but the gateway IP would be reachable).

I think that from the pod perspective having a ```/24``` address is misleading because the corresponding subnet is not L2-reachable and all traffic needs to be routed so it makes more sense to have a ```/32``` and a "routed" interface. That would mean overriding the netmask from the IPAM plugin. Another option would be to modify the IPAM plugin (add a "routed" flag for instance?) but I'm not sure it is worth it.

Of course if some application relies on the information to infer the allocated POD CIDR it would not work anymore (but it would be a little weird no?)

**Comment by rosenhouse** [comment]
For what it's worth, we something like this in [Silk](https://github.com/cloudfoundry/silk):

In the container, `ip addr` shows
```
5805: eth0@if5806: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default
    link/ether ee:ee:0a:ff:0c:41 brd ff:ff:ff:ff:ff:ff
    inet 10.255.12.65 peer 169.254.0.1/32 scope link eth0
       valid_lft forever preferred_lft forever
```
and `ip route` shows
```
default via 169.254.0.1 dev eth0  src 10.255.12.65
169.254.0.1 dev eth0  proto kernel  scope link  src 10.255.12.65
```

On the host, `ip addr`
```
5806: s-010255012065@if5805: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default
    link/ether aa:aa:0a:ff:0c:41 brd ff:ff:ff:ff:ff:ff link-netnsid 10
    inet 169.254.0.1 peer 10.255.12.65/32 scope link s-010255012065
       valid_lft forever preferred_lft forever
```
and `ip route`:
```
10.255.12.65 dev s-010255012065  proto kernel  scope link  src 169.254.0.1
```

**Comment by jingax10** [comment]
@lbernail I've experimented your idea with /32 in container namespace before and it works, though we have to revise the result returned by IPAM plugin. By taking a closer look, I think the route setup is not bad in container namespace: it is configured in a way that only one ARP entry on behalf of gateway is sufficient for any application to send traffic out of container namespace.

My PR #137 is more concerned about veth setup in host namespace. The changes I did include
- Remove the gateway IP assignment for veth in host namespace;
- Using proxy ARP/NDP to resolve destination MAC address
- Change the veth's route scope from host to link

With the above change, it also enables the new use case such that I can apply policy routing with PTP plugin to emulate VEPA mode. In public cloud, it will be useful to make sure networking features in the fabric layer are always functional even if two containers sit on the same VM.

**Comment by lbernail** [comment]
@jingax10 Yes I agree that not having the gateway IP on all veth on host and using scope link is simpler and easier to grasp. I find the static ARP entry for the "fake" gateway IP a bit misleading because this IP will not be attached to any interface and will not be reachable (not a big deal but one of the first debugging step is often to ping the gateway IP).

I'm not sure I get the last point on VEPA emulation: today with the PTP plugin traffic is routed between pods in the host namespace and routed to the outside world right? So traffic between two pods on the same host should never hit the fabric layer. Do you mean you want the ability to route pod to pod traffic through the fabric layer using ip rule?
