### ISSUE TITLE
IPAM: static & bandwidth binary is not pack in tar

### ISSUE THREAD

**Issue by John-Lin** [containernetworking/plugins#153]
Not sure is it an issue. When using building shell I can build `static` and `bandwidth` binary  
```
~/go/src/github.com/containernetworking/plugins(master) ¬ª ./build.sh                                                             johnlin@Ches-MacBook-Pro
Building plugins
  bandwidth
  flannel
  portmap
  tuning
  bridge
  host-device
  ipvlan
  loopback
  macvlan
  ptp
  vlan
  dhcp
  host-local
  static
  sample
```

But download from [release page](https://github.com/containernetworking/plugins/releases) it seems not pack in to tgz file
```
$ tar -zxf cni-plugins-amd64-v0.7.1.tgz ./
$ ls
bridge cni-plugins-amd64-v0.7.1.tgz  dhcp  flannel  host-device  host-local  ipvlan 
 loopback  macvlan  portmap  ptp  sample  tuning  vlan
```

**Comment by Lion-Wei** [comment]
Friendly ping @squeed @dcbw @rosenhouse, Since already have `bandwidth` package, I think it's good for user to have a new release.
For example, we already have pr "kubelet cni network plugin support traffic shapping", and we do need `bandwidth` package for e2e test.

**Comment by squeed** [comment]
This is because we haven't yet done a release that contains those plugins. We were waiting to release 0.8.0 to incorporate the changes added in CNI spec 0.4.0, which will take a month or so. Do you need the plugins for production now? If not, you can just build them manually.

**Comment by basvandenbrink** [comment]
I just downloaded version 0.7.4 of the CNI-plugins and I noticed that the static plugin has not yet been included. Is there any news on this for future releases? Can this issue be reopened?
