### ISSUE TITLE
dhcp plugin should ship with example systemd .socket file

### ISSUE THREAD

**Issue by dcbw** [containernetworking/plugins#156]
The DHCP plugin can be socket-activated by systemd, but there is no example .socket file for it.  We should add one.

**Comment by onlyjob** [comment]
Perhaps something like this:

**[cni-dhcp.socket](https://salsa.debian.org/go-team/packages/rkt/blob/master/debian/rkt.cni-dhcp.socket)**:
~~~~
[Unit]
Description=CNI DHCP service socket
Documentation=https://github.com/containernetworking/plugins/tree/master/plugins/ipam/dhcp
PartOf=cni-dhcp.service

[Socket]
ListenStream=/run/cni/dhcp.sock
SocketMode=0660
SocketUser=root
SocketGroup=root
RemoveOnStop=true

[Install]
WantedBy=sockets.target
~~~~

**[cni-dhcp.service](https://salsa.debian.org/go-team/packages/rkt/blob/master/debian/rkt.cni-dhcp.service)**:
~~~~
[Unit]
Description=CNI DHCP service
Documentation=https://github.com/containernetworking/plugins/tree/master/plugins/ipam/dhcp
After=network.target cni-dhcp.socket
Requires=cni-dhcp.socket

[Service]
ExecStart=/usr/local/bin/cni/dhcp daemon

[Install]
WantedBy=multi-user.target
~~~~

**Comment by dcbw** [comment]
@onlyjob awesome, thanks for taking a look at this.  Would you be able to put together a quick pull request dropping these files into plugins/ipam/dhcp?

**Comment by onlyjob** [comment]
I can't do pull request at the moment, sorry... Swamped with other things...
