### ISSUE TITLE
IPV6 subnets specified with a full address generate unexpected range

### ISSUE THREAD

**Issue by NeilW** [containernetworking/plugins#161]
host-local IPAM plugin

If I specify a subnet CIDR using a full address, then the range seems to start at that address rather than the default addresses for the range. 

i.e. the code seems to use the address and not the network to allocate the default range.

e.g 

```
{
          "subnet": "2a02:1348:178:7112:24:19ff:fee1:c44a/64"
}
```

Changing the 'should generate sane defaults for ipv6' spec in `allocator/range_test.go` so the subnet string is an address with a mask, not a clean prefix causes the spec to fail.

**Comment by bboreham** [comment]
I'm not familiar with the concept of a "subnet CIDR using a full address" - can you supply a reference?

I would expect a network address to be all zeros after the prefix.

**Comment by NeilW** [comment]
As above - specifying the subnet using a full address in that subnet: "2a02:1348:178:7112:24:19ff:fee1:c44a/64"

The /64 should mask out the host bits whether they are specified or not if the address is used as a network address. The plugin can either discard them and clean up the prefix - which is how I've done it in the attached PR - or if you want you can validate, insist on a clean prefix and throw an error.

As it stands the plugin misbehaves. For some reason the CNI types 'ParseCIDR' function replaces the network address with the specific address

**Comment by NeilW** [comment]
In RFC terms see the top of the page here: https://tools.ietf.org/html/rfc4291#page-6

**Comment by bboreham** [comment]
I read that RFC as saying you can write a node address that way; not that you can write a subnet that way. 

I would agree with throwing an error in this case.

**Comment by NeilW** [comment]
Pretty much everything else in networking just masks the bits and gets on with it. Hence why I did it in the first place. So throwing an error would be atypical in networking terms

**Comment by NeilW** [comment]
If you take the subnet out of an address when specified then I can just grab the address from an interface and stick it in the CNI config. 

If you error I have to take the address from an interface and run it through a python script - which is what I'm doing now to work around the bug

```
declare -a ipv6_array=($(ip -6 -o addr show scope global))
ipv6_prefix=$(python3 -c "import ipaddress; print(ipaddress.ip_interface('$${ipv6_array[3]}').network)")
```

Why impose that extra code, when it is so easy to grab the subnet from the address in accordance with the RFC?

**Comment by bboreham** [comment]
Unfortunately “just mask” is a quiet change which will surprise those people who have entered the desired start address but an incorrect prefix length. 

And I do not agree that the RFC supports your interpretation. 

Let’s see what the other maintainers think.

**Comment by NeilW** [comment]
I've altered the coding to throw an error when the network address is incorrect for the specified subnet mask and added it as a new PR.
It includes changes to a couple of other tests where the IPv6 subnet mask length was incorrect for the prefix specified and which the new code highlighted.
