### ISSUE TITLE
nat: add proper "random" flag to avoid kernel race

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#163]
As mentioned in https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02, the default kernel behavior for inserting snat rules is error-prone. The `--random` flag can mitigate it somewhat, and the `--random-fully` is even more likely to succeed.

The gotcha is that `--random-fully` is only included in the absolute newest release of iptables, v1.6.2. So, we need coreos/go-iptables#48 to land first.

**Comment by squeed** [comment]
We should add this for the DNAT rules for host port mapping too (it supports `--random`)

**Comment by bboreham** [comment]
Some background on the DNAT comment at https://github.com/weaveworks/weave/issues/3287#issuecomment-387178077

**Comment by Quentin-M** [comment]
I just posted a little write-up about our journey troubleshooting the issue, and how we are worked around it in production: https://blog.quentin-machu.fr/2018/06/24/5-15s-dns-lookups-on-kubernetes/.

Implementing `NF_NAT_RANGE_PROTO_RANDOM_FULLY` may not be enough to fix the problem, as it only addresses the SNAT race in my understand, whereas the race also exist with DNAT.

**Comment by qiqizjl** [comment]
hi Is there something new in this matter? I see that the master has updated go-iptables to 0.4.1.
