### ISSUE TITLE
Loopback plugin gives an error "missing network name"

### ISSUE THREAD

**Issue by amshinde** [containernetworking/plugins#167]
We are using the loopback plugin in our CNI tests for Kata Containers. But we are seeing failures running this plugin: "missing network name".
See https://github.com/kata-containers/runtime/pull/385#issuecomment-397922893

**Comment by dcbw** [comment]
Network name has been required in the JSON configuration for a number of years, but due to an oversight was not enforced in the libcni code.  That has been recently fixed.  So just add `"name": "loopback"` to your JSON config and that should work.
