### ISSUE TITLE
firewall plugin should also optionally add rules to INPUT table

### ISSUE THREAD

**Issue by dcbw** [containernetworking/plugins#168]
If a user has their INPUT table default drop packets, then the firewall plugin won't fully allow the container to send/receive traffic. This is relevant for containers that do *not* use hostport/portmapping, but have their container address exposed for services.

@bboreham does this description look sane?

**Comment by dcbw** [comment]
Need to figure out how this would work for firewalld too though.

**Comment by rhatdan** [comment]
@dcbw Any progress?
