### ISSUE TITLE
Split Close() into Remove() and Unmount() functions

### ISSUE THREAD

**Issue by sboeuf** [containernetworking/plugins#18]
We want to be able to unmount the netns on purpose, and remove it when we know we properly unmounted it.
Refer to the discussion here: https://github.com/containernetworking/cni/pull/342

**Comment by squeed** [comment]
I think we just want Close() (which closes the fd) and Unmount(), but, yes, agreed.

**Comment by dcbw** [comment]
Sure, I'll agree with Close/Unmount per @squeed and discussion in https://github.com/containernetworking/cni/pull/342#issuecomment-273814455.
