### ISSUE TITLE
Feature request; Create a pure l2-bridge connected to a physical interface

### ISSUE THREAD

**Issue by SchSeba** [containernetworking/plugins#182]
It will be nice if we can have a pure l2 bridge connected to a physical interface on the host.

Sample:
```
{
	"cniVersion": "0.3.0",
	"type": "l2-bridge",
	"bridge": "mynet0",
	"ipam": {}
}
```

I will like to know if there is something interesting for this repo.

I can open a PR on it.

**Comment by liuzeyusss** [comment]
Compared with MacVlan, in addition to having a cluster ip, is there any other benefit to this approach?
