### ISSUE TITLE
Wrong describe of bandwidth unit

### ISSUE THREAD

**Issue by dongjun666** [containernetworking/plugins#188]
https://github.com/containernetworking/plugins/blob/master/plugins/meta/bandwidth/main.go#L38 
//Bandwidth rate in Kbps for traffic through container.

The unit of bandwidth described is Kbps, which is actually bps.  Cloud I correct this.

**Comment by jellonek** [comment]
Yes, please do a PR.

**Comment by matthewdupre** [comment]
Thanks - merged :)
