### ISSUE TITLE
ipam/dhcp: please allow setting default gateway

### ISSUE THREAD

**Issue by onlyjob** [containernetworking/plugins#192]
Similar to `ipam/host-local` there should be option to set/override default gateway in the `ipam/dhcp`. This is especially important as currently `ipam/dhcp` does not use gateway info from DHCP server.

Lack of gateway in DHCP prevents communication with networks beyond LAN.

**Comment by saravanakumar-periyasamy** [comment]
check this comment - https://github.com/containernetworking/cni/issues/310#issuecomment-363146469

**Comment by saravanakumar-periyasamy** [comment]
may be it can ignore the routes from DHCP and use the override if its explicitly set.

**Comment by dcbw** [comment]
#255 has been merged, so I think this can be closed.
