### ISSUE TITLE
Why did release 0.7.2 and 0.7.3 only have source code?

### ISSUE THREAD

**Issue by gyliu513** [containernetworking/plugins#198]
Unlike 0.7.1 and previous releases https://github.com/containernetworking/plugins/releases/tag/v0.7.1 , the 0.7.2 and 0.7.3 only have source code but no binary, why?

![image](https://user-images.githubusercontent.com/4461983/45070177-a02aa380-b102-11e8-8d9f-452563ba543d.png)

![image](https://user-images.githubusercontent.com/4461983/45070189-b20c4680-b102-11e8-996c-8022e1ea8ace.png)

**Comment by gyliu513** [comment]
FYI @squeed

**Comment by squeed** [comment]
Because of a stupid packaging error on my side. I'm releasing v0.7.4, which is the same as v0.7.1, now.

**Comment by voidengineer** [comment]
Where is this v0.7.4? And should it not be like v0.7.3?

**Comment by den-is** [comment]
> You shaaall not paaaasss !

said once mr v0.7.1 
all new tag equals v0.7.1 :D
