### ISSUE TITLE
Flannel CNI wrong ip assignment

### ISSUE THREAD

**Issue by stgleb** [containernetworking/plugins#208]
I've created cni configuration according to readme for flannel in /etc/cni/net.d

```
{
    "cniVersion": "0.4.0",
    "name": "mynet",
	"type": "flannel"
}
```

But it creates new pods and assign ip addresses to them from docker0 network. I need pods to be assigned with ip addresses from network that flannel interface belongs to. What I do wrong?

**Comment by hwchiu** [comment]
As I know, flannel use the host-local to choose the ip address, could you describe more detail about your environment?

**Comment by stgleb** [comment]
@hwchiu Than you,I've already resolved that, but didn't close the issue.
