### ISSUE TITLE
Handle empty namespace consistently

### ISSUE THREAD

**Issue by Random-Liu** [containernetworking/plugins#210]
In https://github.com/containernetworking/plugins/pull/5, we decided to ignore empty network namespace.

However, this is not handled consistently across different network plugins:
* Plugins that ignore empty namespace and don't return error: `bridge`, `ptp`, `ipvlan`, `macvlan`, `vlan`;
* Plugins that return error if empty namespace is passed in: `loopback`, `host-device`.

Why don't we handle them consistently?

/cc @jingax10

**Comment by rosenhouse** [comment]
What’s the use case for empty namespace?

**Comment by Random-Liu** [comment]
This is also defined in the new CNI spec https://github.com/containernetworking/cni/commit/23a5d8e617027c87a84605426c3b228931c69826
