### ISSUE TITLE
There is no documentation for building Windows CNI plugins

### ISSUE THREAD

**Issue by pjh** [containernetworking/plugins#224]
`CONTRIBUTING.md` explains how to build plugins but simply invoking `build.sh` does not build the Windows plugins.

`plugins/main/windows/win-bridge/README.md` and `plugins/main/windows/win-overlay/README.md` do not explain how to build the plugins.

After poking around for a minute I found `plugins/main/windows/build.sh`, but I'm getting an error when I try to run it:

```
$ GO=$(which go) plugins/main/windows/build.sh 
  host-local.exe
can't load package: package /plugins/ipam/host-local: import "/plugins/ipam/host-local": cannot import absolute path
```

I'm not sure if I'm doing something wrong or if this is a legitimate build error. I'm also not sure if I should be attempting to build these plugins on a Linux machine or a Windows machine, or if either is fine.

After writing all of this I finally found the change to `build.sh` in https://github.com/containernetworking/plugins/pull/193/files which suggests that perhaps I just need to set GOOS and GOARCH before invoking the top-level build script.

On the whole some step-by-step instructions for building and hacking on these plugins would be appreciated. @rakelkar @madhanrm @PatrickLang @dineshgovindasamy

**Comment by rosenhouse** [comment]
You may also be interested in #219

**Comment by pjh** [comment]
Thanks a lot, hadn't seen that PR yet, I'll see if it works for me.
