### ISSUE TITLE
Portmap plugin fails with Debian iptables v1.8.1

### ISSUE THREAD

**Issue by dkoshkin** [containernetworking/plugins#225]
When trying to setup a pod with `hostPort`, the portmap CNI plugin fails with:
```
Warning  FailedCreatePodSandBox  108s                 kubelet, kube-node-public-0-kubelet  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "5a572019b130209679e245deafec67238e3be22ae67cee6b0f5a519db4ee1af3" network for pod "traefik-h74xh": NetworkPlugin cni failed to set up pod "traefik-h74xh_test-ingress" network: unable to create chain CNI-HOSTPORT-SETMARK: running [/usr/sbin/iptables -t nat -I POSTROUTING 1 -m comment --comment CNI portfwd requiring masquerade -j CNI-HOSTPORT-MASQ --wait]: exit status 4: iptables v1.8.1 (nf_tables):  RULE_INSERT failed (Invalid argument): rule in chain POSTROUTING
```

There is a related issue in docker: https://github.com/moby/moby/issues/38099

Docker's fix is first trying to use `iptables-legacy` and then the `ipatbles` binary seems pretty sane but I don't have enough context for this project to know if that will be acceptable here:
https://github.com/thaJeztah/docker/blob/87558ad4dd93006b4935a673dee273d4687cc495/vendor/github.com/docker/libnetwork/iptables/iptables.go#L89-L107

## Versions
* iptables version in question:
```
$ iptables --version
iptables v1.8.1 (nf_tables)
```
* kubernetes `v1.12.2`
* Calico `v3.3` with CNI plugin `v0.7.1` https://github.com/projectcalico/cni-plugin/blob/release-v3.3/Makefile#L76

**Comment by squeed** [comment]
ew, forcing iptables-legacy is the wrong solution! let's see if this is a bug in `nft-compat` or if we're doing something stupid here.

**Comment by dkoshkin** [comment]
Actually it looks like the vendored `go-iptables` has some changes around `nftables` https://github.com/coreos/go-iptables/pull/51 and released in https://github.com/coreos/go-iptables/releases/tag/v0.4.0 but Im not seeing how to update the dep to test it out.

**Comment by squeed** [comment]
I wrote those :-).
I reverted all those changes as the iptables maintainers fixed the incompatibilities. But it seems that there is either another iptables bug, or something simply unsupported.

**Comment by dcbw** [comment]
Is this still an issue with latest iptables releases?
