### ISSUE TITLE
Clear up context.TODO() calls

### ISSUE THREAD

**Issue by bboreham** [containernetworking/plugins#228]
Some calls to `context.TODO()` were added in #227: we need to decide what context they should be, and use that one instead.

**Comment by mars1024** [comment]
@bboreham I'm trying to fix this, maybe we can have a further discussion in PR ~

**Comment by bboreham** [comment]
Sure, what do you think?

**Comment by mars1024** [comment]
@bboreham  I'm trying to use a timeout context for legacy functions and add some new functions with context as input parameter. Later we can push CNI plugins to use context framework.
