### ISSUE TITLE
Portmap not working with host VLANs

### ISSUE THREAD

**Issue by CallMeFoxie** [containernetworking/plugins#230]
Hi
it seems that portmap doesn't work with VLANs because of this:
https://github.com/containernetworking/plugins/blob/master/plugins/meta/portmap/portmap.go#L274
where `ifName = "eth0.798"` for example
which gets fed to
https://github.com/containernetworking/plugins/blob/master/pkg/utils/sysctl/sysctl_linux.go#L49
where all the dots are replaced with slashes and thus you get path of `eth0/798` instead of `eth0.798`. 

:)
Thanks for looking at it.
Cheers, Ashley

**Comment by squeed** [comment]
Wow, weird! Good find...

**Comment by camrossi** [comment]
I am hitting the same issue as well, I assume no one had time to work on this?
I just renamed the interfaces to vlanXXX as a workaround and that worked fine.
