### ISSUE TITLE
Windows Binaries in Releases

### ISSUE THREAD

**Issue by astrieanna** [containernetworking/plugins#232]
Given that there are now a couple of [windows CNI plugins](https://github.com/containernetworking/plugins/pull/193), could those be included in the binaries for the github releases?

The relevant binaries are:
- flannel.exe
- host-local.exe
- win-overlay.exe
- win-bridge.exe

**Comment by feiskyer** [comment]
+1

**Comment by bboreham** [comment]
It looks to me like the release script will already make the Windows binaries:
https://github.com/containernetworking/plugins/blob/master/scripts/release.sh#L34-L39

**Comment by astrieanna** [comment]
@bboreham The most recent release on Github still doesn't have any tarballs for windows and the tarballs for windows architectures do not contain windows binaries.

**Comment by benmoss** [comment]
Looks like it was released from the v0.7 branch, should we backport the changes to `release.sh` to that branch?

**Comment by bboreham** [comment]
I doubt if that will make people happy - you'd get the Windows plugin code as at a year ago.
More likely you want the Windows plugin code that has been changed extensively over the last few months, which would be a 0.8.0 release.  Coming soon...

**Comment by benmoss** [comment]
Any time frame on this? It'd be nice to be able to ship official binaries.
