### ISSUE TITLE
DHCP daemon should remember leases over a restart

### ISSUE THREAD

**Issue by bboreham** [containernetworking/plugins#235]
Currently it forgets everything on restart, so leases will all time out soon.

Noted at https://github.com/containernetworking/plugins/pull/217#issuecomment-440729282

**Comment by ajacques** [comment]
Are there any further thoughts on remembering leases over a restart? Is this something that the CNI group would want fixed?

My approach is every time a new lease allocated, I save all of the leases to a local file. When the daemon starts up reload that file and start maintaining those leases. [My fork](https://github.com/ajacques/cni-plugins/tree/dhcp-remember-leases)

However, there's an edge case if another container shuts down while the DHCP daemon is offline, then the daemon could keep maintaining a lease to a dead container. I considered querying Dockerd to see if that container is still running, but with K8s moving towards containerd, that might be too coupled. Another option would be to have the DHCP IPAM call the k8s API server and try to find a pod matching that container id. Is that an okay dependency? Is there a better way to handle this edge case?
