### ISSUE TITLE
Bridge plugin: how to avoid NAT in pod-to-pod communication between diffirent hosts?

### ISSUE THREAD

**Issue by varuzam** [containernetworking/plugins#240]
Hello.
I am trying to get kubenet functionality with bridge plugin.
My configs
**Node1**
```
{
    "name": "kube-main",
    "type": "bridge",
    "bridge": "kube-main",
    "isGateway": true,
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "ranges": [
          [{"subnet": "172.18.1.0/24"}]
        ],
        "routes": [{"dst": "0.0.0.0/0"}]
    }
}
```
**Node2**
```
{
    "name": "kube-main",
    "type": "bridge",
    "bridge": "kube-main",
    "isGateway": true,
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "ranges": [
          [{"subnet": "172.18.2.0/24"}]
        ],
        "routes": [{"dst": "0.0.0.0/0"}]
    }
}
```

In this case All traffic between Node1's pods and Node2's pods is going through NAT.  If ipMasq=false it does not use NAT but all networks outside  172.18.1.0/24 and 172.18.2.0/24 become unavailable.

**Comment by dcbw** [comment]
You would either add eth0 of each node to the bridge so that the containers can talk directly via L2, or use something like Flannel to provide direct IP-level routing between nodes.
