### ISSUE TITLE
cni vlan plugin not suppor 2 pod

### ISSUE THREAD

**Issue by PengTaoWW** [containernetworking/plugins#243]
{
        "cniVersion": "0.3.0",
        "name": "mynet",
        "type": "vlan",
        "vlanId": 200,
        "master": "eth1",
        "ipam": {
                "type": "host-local",
                "subnet": "10.141.0.0/24",
                "gateway": "10.141.0.1"
        }
}

when i pod number > 1, will fail .report network: failed to create vlan: file exists"

**Comment by dcbw** [comment]
@PengTaoWW yes, that's a limitation of the Linux VLAN interface. If you want multiple pods on the same VLAN you need to use the bridge plugin, but create a manual vlan and attach that to the bridge as a port. Alternatively, there is https://github.com/containernetworking/plugins/pull/231
