### ISSUE TITLE
Create a docker image for easy deployment of binaries

### ISSUE THREAD

**Issue by micw** [containernetworking/plugins#244]
There should be a docker images so that the binaries can easily be deployed using a kubernetes job or daemonset.

**Comment by micw** [comment]
I have created the Dockerfile. It was quite easy since the build script is already there. I'd appreciate if you could create an official docker hub repo for it.
If you accept the PR, I'll also use the docker image to finally fix https://github.com/intel/multus-cni/issues/192

**Comment by bboreham** [comment]
How do you envisage the binaries inside a container will be executed by the runtime?

Perhaps you could comment on https://github.com/containernetworking/cni/issues/284

**Comment by micw** [comment]
@bboreham That's an interesting discussion. But I get the impression that it went the wrong way (adding more complexity, making cni plugins more smart about how to find and call other plug-ins).
The latest comment (https://github.com/containernetworking/cni/issues/284#issuecomment-240950145) shows a very good idea how this could be done. One container that manage the references plug-ins could be a building brick to achive this.
When this is done, multus could profit a lot of it. Rather than calling other CNI Plug-Ins it would just need to tell the lib which to call.

But it will require a big design change in both, cni and multus - so it will take time to do this. Meanwhile I'd just pack the binaries to a container and install it into /opt/cni/bin.

**Comment by bboreham** [comment]
>  just pack the binaries to a container and install it into /opt/cni/bin.

I don’t get what you mean here. Please explain step by step. 

Also how does this fit with “deployed using a kubernetes job or daemonset“?

**Comment by micw** [comment]
@bboreham Sorry for delay, I'll explain:

The most common way, cni plug-ins are currently installed to kubernetes clusters is the following:
Someone who wrote a CNI packs the plug-ins into a container. On cni startup (in most cases on an initContainer), the host's /opt/cni/bin is mounted into a container and a script within the container copies the plug-ins to this directory. Then this plug-in (and maybe other, nested cni plug-ins) can not access the binaries by mounting the host's /opt/cni/bin directory.

Since there's no official docker image that contains the default cni plug-ins, each cni plug-in packs a copy of the default plug-ins it needs. Flannel for example ships a copy of the "hostlocal" plug-in as well as some others - but not all.

If we had an official docker image, this could be used to install the default plug-ins.

I have created an inofficial one and added it to the multus-cni. This is a good example how the docker image can be used: https://github.com/intel/multus-cni/pull/207/files

**Comment by bboreham** [comment]
Ok; I am used to a different workflow where the Kubernetes installer (eg kubeadm) installs the base plugins from a package.
