### ISSUE TITLE
ip can not auto release when hostnode reboot

### ISSUE THREAD

**Issue by kadisi** [containernetworking/plugins#252]
i use host-local ipam to allocate ip for container , but , if host node is shutdown or reboot, container will be recreate , but there will leave some not recycled ip beacuse cni not exec `cmdDel`。if host node shutdown many times, it will waste a lot of ip.

**Comment by jellonek** [comment]
In case of node reboot you need to empty `/var/lib/cni/networks/NETWORK_NAME` directory, where NETOWORK_NAME is name of the cni network which is using `host-local` ipam (as defined in `/etc/cni/net.d/` configuration).

**Comment by kadisi** [comment]
@jellonek i know, i mean  is whether `host-local` ipam is able to determine whether IP is wasteful and reusable, i hope `host-local ` ipam can judge it.  because we do not known when the node will reboot
 t

**Comment by jellonek** [comment]
There is no way to determine which IP addresses are still in use from ipam level. ipam only serves the data and it's up to upper plugin to consume/use it. Upper level caller can do whatever it wants with this data so there is no any guarantee that it will be instantly applied to node, on which that was called, or even more - this data can be used to configure VM on this node in which case configuration would go to kernel on VM, so at the end would be invisible from level accessible to ipam.
