### ISSUE TITLE
how to test macvlan from the command line

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/plugins#257]
I would like to test if macvlan can find all required binaries. The bridge plugin works, but it the same config the macvlan does not. I think maybe some os dependencies need  to be installed.

[@m02 cni]# ./macvlan -h
CNI_COMMAND env variable missing
{
    "code": 100,
    "msg": "required env variables missing"

**Comment by squeed** [comment]
macvlan is statically compiled, which you can verify with `ldd`. You can also test it by using cnitool.
