### ISSUE TITLE
bandwidth should be more careful about finding host-side veth pair

### ISSUE THREAD

**Issue by dcbw** [containernetworking/plugins#260]
Bandwidth currently does this in getHostInterface():

```
	var err error
	for _, iface := range interfaces {
		if iface.Sandbox == "" { // host interface
			_, _, err = ip.GetVethPeerIfindex(iface.Name)
			if err == nil {
				return iface, err
			}
		}
	}
```

It should instead look for the sandbox interface, run GetVethPeerIfindex() on that inside the container namespace to get the ifindex of the host side, and then look up the host-side ifname using that ifindex.

The problem is that some plugins (eg https://github.com/containernetworking/plugins/pull/231) may return multiple host-side veth interfaces, only one of which is the container veth. Bandwidth doesn't filter the interfaces enough to figure that out.

**Comment by mars1024** [comment]
try to fix in #321
