### ISSUE TITLE
Don't allocated mac address with reserved value 0xFE 

### ISSUE THREAD

**Issue by SchSeba** [containernetworking/plugins#280]
There are programs that can't work with any mac address.
One of the is qemu when you try to configure the mac address that start with `FE` it will fail.

I will like to open a PR to change the `makeVethPair` function https://github.com/containernetworking/plugins/blob/master/pkg/ip/link_linux.go#L34 

to exclude this prefix.
before I implement it I will like to know if this is something that can be accepted in this repo.

**Comment by dcbw** [comment]
@SchSeba yes, we'd like to see a PR that would address this issue. But isn't the MAC address generated by the kernel and we don't have any control over it in CNI?

**Comment by SchSeba** [comment]
@dcbw thanks for the comment.

yes the mac is generated by the kernel so I see here 2 ways to implement a fix for this.

if the mac start with 0xFE
1. for loop to generate the mac again (we should configure a limit here of course)
2. generate a random prefix and check that the new mac doesn't already exist if exist loop generate a new prefix

I will like to know if the sounds good or you have a better solution for this issue.
