### ISSUE TITLE
Flannel plugin doesn't delegate runtimeConfig

### ISSUE THREAD

**Issue by benmoss** [containernetworking/plugins#305]
I'm trying to use `runtimeConfig` to set custom DNS on a pod scheduled by Kubernetes. When using flannel as my CNI, the `runtimeConfig` properties get sent to flannel, but it doesn't pass them on to the delegate plugin. I looked at the code and it seems like there isn't a way to do this.

Is this intentional?

**Comment by nagiesek** [comment]
No this a bug, flannel doesn't propogate runtimeConfig down, I have a fix, but I'm not sure what correct approach is.

**Comment by nagiesek** [comment]
https://github.com/containernetworking/plugins/pull/309
