### ISSUE TITLE
cmdDel how to optain the currently assigned ipam addresses?

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/plugins#306]
Within the cmdAdd you can get the assigned ip addresses via

```
result, err := ipam.ExecAdd(n.IPAM.Type, args.StdinData)
result.IPs
```

But what is the best way to retrieve these addresses in cmdDel function? Are these available in some variable? Or do you need to get them from the interfaces in the namespace manually?

**Comment by dcbw** [comment]
@f1-outsourcing with CNI 0.4.0 spec (which is part of the github.com/containernetworking/cni repo 0.7.0 release) the DEL command now gets a 'prevResult' item in its JSON config that you can use to determine the result of the previous ADD command. A number of plugins in this 'plugins' repo currently use that functionality:

https://github.com/containernetworking/plugins/blob/a03e6b505e9903cfffe0fcba6ab41c18ef4a06fa/plugins/meta/firewall/firewall.go#L65

That example uses standard libcni functions to retrieve and parse the prevResult which you can then use to get the address assigned to CNI_IFNAME.
