### ISSUE TITLE
go module import pkg not found

### ISSUE THREAD

**Issue by Colstuwjx** [containernetworking/plugins#308]
Hi team,

I'm trying use plugins package to define my own cni plugin, and meet issue likes below:

```
go: finding github.com/containernetworking/plugins/pkg/utils/buildversion latest
go: finding github.com/containernetworking/plugins/pkg/utils latest
go: finding github.com/containernetworking/plugins/pkg latest
build cerberus/plugin/ipam: cannot load github.com/containernetworking/plugins/pkg/utils/buildversion: cannot find module providing package github.com/containernetworking/plugins/pkg/utils/buildversion
```

I'm wondering whether add `go.mod` in our repo could fix this issue?
Thanks.

**Comment by bboreham** [comment]
I suspect that the problem is there is no tagged version containing `plugins/pkg/utils/buildversion`.

Probably you can override to use the tip version, or select a compatible set of versions.
