### ISSUE TITLE
type of `IPConfig.Interface` is changed in `containernetworking/cni`

### ISSUE THREAD

**Issue by flyer103** [containernetworking/plugins#31]
This PR https://github.com/containernetworking/cni/pull/477  has changed the type of `IPConfig.Interface` from `int` to `*int`.
If `containernetworking/plugins` updates vendered pkg, it may cause https://github.com/containernetworking/plugins/blob/master/pkg/ipam/ipam.go#L56 not working.

The PR https://github.com/containernetworking/cni/pull/477 is rational, but `containernetworking/plugins` does not catch up with `containernetworking/cni`. And if someone develops an ipam plugin and use vendoring in his project which will vendor `containernetworking/cni` and `containernetworking/plugins`, he may find that https://github.com/containernetworking/plugins/blob/master/pkg/ipam/ipam.go#L56 cause his ipam plugin couldn't be compiled.
So is it necessay to vendor `containernetworking/cni` in `containernetworking/plugins`, or is there a way to catch up with `containernetworking/cni`?

**Comment by squeed** [comment]
I don't think there's anything we can do about this. The plugins aren't really meant to be vendored in. However, if there's a need for some primitives such as `setupVeth` that are higher-level, then we should consider extracting them.
