### ISSUE TITLE
plugins latest version code not match with cni latest version

### ISSUE THREAD

**Issue by Colstuwjx** [containernetworking/plugins#313]
Hi team,

I'm using [plugins](https://github.com/containernetworking/plugins) repo and [cni](https://github.com/containernetworking/cni) repo to write my own cni plugin, and I met some issues on build.

My go module spec likes below:

```
...

require (
	github.com/containernetworking/cni v0.7.0
	github.com/containernetworking/plugins v0.7.5
        ...
)
```

While `cni == v0.7.0 && plugins == v0.7.5`,  some function calls builds failed:
```
# github.com/containernetworking/plugins/pkg/ipam
../../../../Go/pkg/mod/github.com/containernetworking/plugins@v0.7.5/pkg/ipam/ipam.go:23:27: not enough arguments in call to invoke.DelegateAdd
	have (string, []byte)
	want (context.Context, string, []byte, invoke.Exec)
../../../../Go/pkg/mod/github.com/containernetworking/plugins@v0.7.5/pkg/ipam/ipam.go:27:27: not enough arguments in call to invoke.DelegateDel
	have (string, []byte)
	want (context.Context, string, []byte, invoke.Exec)
```

Maybe we need to add another newer tag for plugins, since the latest version v0.7.5 is also too old towards cni repo.
Thanks!

**Comment by dcbw** [comment]
Plugins v0.7.5 is older than cni v0.7.0, so you either need to (a) revert to an older compatible CNI version or (b) allow plugins to use its internal vendored copy of cni.
