### ISSUE TITLE
 failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod

### ISSUE THREAD

**Issue by xiaoqge** [containernetworking/plugins#315]
I use macvlan for kubernetes to manage the network.
I am using macvlan and I get the following error.

` failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "nm-135_default": CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container`
I don't know where there is a problem or how can I find the problem?

**Comment by dcbw** [comment]
This is a problem with the runtime you are using (kubernetes), not CNI itself. This  message comes from Kubernetes dockershim code.
