### ISSUE TITLE
host-device plugin doesn't work with virtio interfaces

### ISSUE THREAD

**Issue by pperiyasamy** [containernetworking/plugins#320]
The existing host-device CNI plugin isn't made to work with virtio interfaces inside a VM (Kubernetes worker node).  The following error is seen while creating k8s POD.

`  Warning  FailedCreatePodSandBox  37s               kubelet, my-centos  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "a9635a3fad602b0d6172a52010b1e01695e99f1372d1054413edecfb73c5b82e" network for pod "testpod1": NetworkPlugin cni failed to set up pod "testpod1_default" network: Multus: Err adding pod to network "host-device-network": Multus: error in invoke Delegate add - "host-device": failed to find host device: no net directory under pci device 0000:00:14.0: "lstat /sys/bus/pci/devices/0000:00:14.0/net: no such file or directory", failed to clean up sandbox container "a9635a3fad602b0d6172a52010b1e01695e99f1372d1054413edecfb73c5b82e" network for pod "testpod1": NetworkPlugin cni failed to teardown pod "testpod1_default" network: Multus: error in invoke Delegate del - "host-device": failed to find "net2": Link not found / Multus: error in invoke Delegate del - "host-device": failed to find "net1": Link not found]`

It is looking for net directory at /sys/bus/pci/devices/0000:00:14.0, but for virtio device (0000:00:14.0) resides under /sys/bus/pci/devices/0000:00:14.0/virtio<<vf_id>> directory.

**Comment by pperiyasamy** [comment]
Fixed the issue with #453

**Comment by VamshiKrishnaNemalikonda** [comment]
I see similar issue - can someone suggest. I'm using Multus + host-device. Thank you

`Warning  FailedCreatePodSandBox  28s (x60 over 9m17s)  kubelet, localhost  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = "/var/run/dockershim.sock": rpc error: code = 2 desc = [failed to set up sandbox container "d9438ea82ee85945c5a033f358e74ec2478068abad6bcdb56ba48d434d11c0a9" network for pod "firewall-host-netdevice2-76b7984f89-2bphh": NetworkPlugin cni failed to set up pod "firewall-host-netdevice2-76b7984f89-2bphh_default" network: Multus: Err adding pod to network "host-device-veth12": Multus: error in invoke Delegate add - "host-device": failed to find host device: Link not found, failed to clean up sandbox container "d9438ea82ee85945c5a033f358e74ec2478068abad6bcdb56ba48d434d11c0a9" network for pod "firewall-host-netdevice2-76b7984f89-2bphh": NetworkPlugin cni failed to teardown pod "firewall-host-netdevice2-76b7984f89-2bphh_default" network: Multus: error in invoke Delegate del - "host-device": failed to find "veth21": Link not found / Multus: error in invoke Delegate del - "host-device": failed to find "veth12": Link not found]`

**Comment by pperiyasamy** [comment]
@VamshiKrishnaNemalikonda How do you pass virtio interface info in net-attach-def ? is it through `device `parameter ?  Can you try to pass it using `pciBusID `parameter? This [PR ](https://github.com/containernetworking/plugins/pull/453)addresses this parameter for virtio net devices.
