### ISSUE TITLE
host-local should support idempotent allocation

### ISSUE THREAD

**Issue by mars1024** [containernetworking/plugins#327]
I think host-local plugin should support idempotent allocation, which means that if we try to request an IP with same container ID several times, the allocator should return the same IP at any time unless we free it.

This will help to avoid **ip leak**. Specially in this scenario, [CRI supports set up the same sandbox container again and again if it exists and its network has not been configured successfully](https://github.com/alibaba/pouch/blob/29753d7d218380b3459ed9e607e1898492bfedab/cri/v1alpha2/cri.go#L363).

**Comment by squeed** [comment]
Hmm. The spec, as written, says that runtimes can only call ADD once. That was part of the motivation for creating the CHECK action, so they could see that networking was still up.

I don't think we want to change the spec to allow idempotency. This is mostly because it's difficult to imagine how certain plugins could implement all of their functionality - along with chained plugins - in an idempotent way.

For example, the `sbr` chained-plugin deletes the routes created by, say, `ptp`. If we were to re-run ADD, then the routing table would be either broken or misconfigured as the process proceeded.

So, I don't think there's a safe-way to re-ADD an existing container.

**Comment by mars1024** [comment]
Thanks for you comment, @squeed , I still think idempotency should be one of basic abilities which an IPAM server should have, it does not sound reasonable for allocator to allocate different IPs for several request with same sandbox ID.
I also think re-ADD is not safe, but it's, maybe, CRI's job to deal with it with some special operation like stopping sandbox container ? Anyway, I don't really care about it. 
What I care about is making `host-local` plugin more robust in some extreme cases like above, and I think this change does not affect any existing behavior or usage, it's more like a nice-to-have feature to make `host-local` a real IPAM server.

**Comment by dcbw** [comment]
@mars1024 the CNI spec requires that ADD only be called once per container. Thus there is no possibility that ADD will be called twice for the same container ID, ifname, and network name.

**Comment by jellonek** [comment]
That also means the spec does not handle ADD/DEL/ADD sequence and for sure at least telecoms need such functionality like dynamic reconfiguration without killing of the container.

**Comment by mars1024** [comment]
Just as I talked above, without regard of the reasonable or unreasonable usage scenarios, what I want to do is just making `host-local` more robust in any possible scenario with minimal cost. I  think it's an **enhancement** rather than a **fix**.
If the issue is not accepted after reconsideration, I'll close this ~
Please pay another attention to this issue and PR in maintainer meeting of this week, thanks ~ @dcbw  @squeed

**Comment by rosenhouse** [comment]
Did you mean to close this issue?  With #328 it seems that you still want to make allocation idempotent on a given primary key of `container ID, ifname, network name`

**Comment by mars1024** [comment]
> Did you mean to close this issue? With #328 it seems that you still want to make allocation idempotent on a given primary key of `container ID, ifname, network name`

Yes, but the idempotency of #328 means returning error instead of returning last-allocated IP, just as the [discussion](https://github.com/containernetworking/plugins/pull/328#issuecomment-508155249).
