### ISSUE TITLE
host-local  ip leak

### ISSUE THREAD

**Issue by hongli-my** [containernetworking/plugins#332]
here only check  file exist, but some case: shutdown... do not call cni del.
https://github.com/containernetworking/plugins/blob/fe60fcddb897079746ec1523fd1837ab05b1e689/plugins/ipam/host-local/backend/disk/backend.go#L63

```
func (s *Store) Reserve(id string, ifname string, ip net.IP, rangeID string) (bool, error) {
	fname := GetEscapedPath(s.dataDir, ip.String())

	f, err := os.OpenFile(fname, os.O_RDWR|os.O_EXCL|os.O_CREATE, 0644)
	if os.IsExist(err) {
		return false, nil
	}
```

**Comment by jellonek** [comment]
It's known simplification from the beginning. It's leaved up to a system administrator to remove leases file during boot sequence.
