### ISSUE TITLE
Tuning plugin: how to use prevResult in tuning plugin

### ISSUE THREAD

**Issue by Purushotham233** [containernetworking/plugins#334]
We are using bridge plugin, but we want to control the mac address of the containers. We were hoping there is some way to consume the ip from the bridge output and generate mac address in tuning plugin.

But as per the code of tuning plugin, I dont see it using the prevResult while parsing the tuning configuration. Please advise if there is any way to do it.

**Comment by mccv1r0** [comment]
You should be able to set the MAC to what you want via the tuning plugin:  

(https://github.com/containernetworking/plugins/tree/master/plugins/meta/tuning#interface-attribute-operation)

**Comment by Purushotham233** [comment]
@mccv1r0 
Lemme clarify our use-case. In our case, bridge plugin is assigning an IP to the container and we want to derive that mac address from the assigned IP and set to the container. 

In the example you shared, the actual mac address to be assigned is provided in the config. In our case, the mac address is a function of the IP(which needs to be derived from the prevResult).

**Comment by squeed** [comment]
The tuning plugin is relatively simple, so it won't be able to do what you want. I'd suggest writing your own chained plugin - using tuning as a basis. It shouldn't be more than a few hundred lines of code.

**Comment by Purushotham233** [comment]
@squeed,
Got it.
Need one clarification here, in what scenario/case user would use tuning plugin for changing mac. Since the mac configuration can take only one specific value and it can only be used for one single container. Or is it the case, somehow the configuration is being generated dynamically before the tuning plugin is invoked for a container?

**Comment by Purushotham233** [comment]
@squeed 

We wrote the custom plugin to change the mac id based on the tuning plugin. 

In the tuning plugin after changing the mac we are bringing the link down and then up. In this process, the default is removed when we bring the link down but it is not added back when bring the link up. In the tuning plugin, I dont see any code to restore back the routes after restarting the link.

What do you recommend to restore the routes? One way is, use the routes from the prevResult and populate them again like we do in the bridge(main) plugin. This can be done but would prefer not to repeat the same thing.
