### ISSUE TITLE
do we need a ipam plugin based on rpc

### ISSUE THREAD

**Issue by mars1024** [containernetworking/plugins#339]
Recently I'm working on a CNI plugin which need to use a global centralized IPAM, and I implemented a client/server IPAM framework based on grpc, I'm wondering if we need a generic rpc-based IPAM plugin, which including a rpc proto file and a CNI plugin which allocate/release IP through grpc.
The rpc proto file is just like below, I think we can make it a standard,
```
service IPAMService {
    rpc AllocateIP (AllocateIPRequest) returns (AllocateIPResponse) {}
    rpc ReleaseIP (ReleaseIPRequest) returns (ReleaseIPResponse) {}
}

message AllocateIPRequest {
    string PodName = 1;
    string PodNamespace = 2;
    string SandboxID = 3;
    string NetNS = 4;
    string IfName = 5;
}
...
```

Then, we can build a centralized IPAM server based on **IPAMService** in proto file, after that, we can use it easily with this plugin.

Anyone has some suggestions?

**Comment by MikeZappa87** [comment]
@mars1024 as I am looking at rpc right now. Possibly we could revive the rpc efforts.
