### ISSUE TITLE
Do we need clean up the the netns after test suit

### ISSUE THREAD

**Issue by smarkm** [containernetworking/plugins#342]
after test suit will remain lost of tmp netns under `/var/run/netns/`, do we need auto clean those ns?

**Comment by dcbw** [comment]
@smarkm that would be nice, yes. Can you prepare a patch?

**Comment by dcbw** [comment]
Perhaps we have some testcases that are forgetting to call <netns>.Close() in the AfterEach().

**Comment by smarkm** [comment]
Ok @dcbw, I will try to do it
