### ISSUE TITLE
Travis CI build are failing for Linux amd64

### ISSUE THREAD

**Issue by mike1808** [containernetworking/plugins#350]
I noticed that for the past 3 months the build for Linux amd64 is failing for the master branch. After looking around I noticed that it happens because of Coveralls (as it only runs for the amd64 target on Linux). And there is this open issue for Coveralls with the exact error message https://github.com/lemurheavy/coveralls-public/issues/1291

Do you use the test coverage for the plugins repo (as I didn't see coverage badge in README)? If yes, do you think, we can copy test.sh from cni repo to this one? Or we can just disable Coverall integration with the plugins repo.

cc @rosenhouse

**Comment by dcbw** [comment]
@mike1808 do you mean when you run test.sh manually? or in travis?

**Comment by jellonek** [comment]
https://travis-ci.org/containernetworking/plugins/builds/553821357 example travis build which failed.

**Comment by mike1808** [comment]
The issue is resolved, seems like it was a regression with Coveralls.
