### ISSUE TITLE
macvlan dhcp master is not work

### ISSUE THREAD

**Issue by X-Mars** [containernetworking/plugins#362]
hello friend，
this is my cni config，
```
[root@fs-worker23 net.d]# cat /etc/cni/net.d/10-macvlan.conf
{
        "name": "macvlannet",
        "type": "macvlan",
        "mode": "bridge",
        "master": "eno1",
        "ipam": {
                "type": "dhcp"
        }
}
```
when start the DHCP , I got an error.
```
2019/08/05 18:57:34 Link "eth0" down. Attempting to set up
2019/08/05 18:57:34 network is down
2019/08/05 18:57:39 1dc47fe9fe7664b3976273402f634d23588bf24665f908f1d95c2943ebb59901/macvlannet: lease acquired, expiration is 2019-08-06 18:57:39.172681718 +0800 CST m=+86733.853612158
2019/08/05 18:57:39 1dc47fe9fe7664b3976273402f634d23588bf24665f908f1d95c2943ebb59901/macvlannet: releasing lease
2019/08/05 18:57:40 07ae69fa9effe4ae415a3f348045f6a03b715a554f45e64e7bfbec02afbfdb01/macvlannet: acquiring lease
2019/08/05 18:57:40 Link "eth0" down. Attempting to set up
2019/08/05 18:57:40 network is down
2019/08/05 18:57:46 network is down
2019/08/05 18:57:47 bb9c60c4d9e54e1a7b75f13d48b7e3a8a9524fc0e0bdc8c1c22d4fb58335fdf3/macvlannet: acquiring lease
2019/08/05 18:57:47 Link "eth0" down. Attempting to set up
2019/08/05 18:57:47 network is down
```

MASTER option is  not work

Thank you for your contribution.

Mars

**Comment by spali** [comment]
I'm not an expert. Currently also working on getting into this topic.
But as I know (or how I interpreted it), eth0 in your log, refers to the interface name inside the container. It's not related to the master interface name.

**Comment by X-Mars** [comment]
> I'm not an expert. Currently also working on getting into this topic.
> But as I know (or how I interpreted it), eth0 in your log, refers to the interface name inside the container. It's not related to the master interface name.

Thank you very much,  my brother.
I use 'static' at last, and upgrade 'macvlan' by my sale.
It can now meet my business needs
