### ISSUE TITLE
how to 'clean up' /var/lib/cni/networks/

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/plugins#365]
I have had now a few times that ip addresses stay in the folder /var/lib/cni/networks/ while tasks are destroyed or suspended. 
When I test with an individual task, scaling creates and releases ip addresses as expected. I do wonder why sometimes ip addresses can be kept registered.

**Comment by smarkm** [comment]
@f1-outsourcing please give more information about your task

**Comment by f1-outsourcing** [comment]
I was not able to reproduce it. I think it is related maybe to dual network use. I have some tasks that are on 2 ip ranges. I noticed that mesos-dns is not even handling dual network properly (they return the last ip address, pffff). So I wonder if this is properly tested.
