### ISSUE TITLE
ipam dhcp 

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/plugins#367]
Is it possible to send arguments to the dhcp server? Eg. to identify applications without the necessity to use pre-configured mac addresses.

like dhcp-client-identifier, host-name and fqdn.fqdn

see https://linux.die.net/man/8/dhclient

**Comment by jellonek** [comment]
It could be optionally added somewhere around https://github.com/containernetworking/plugins/blob/d577d9cc24542f28f0070b197964890f2f011ff8/plugins/ipam/dhcp/lease.go#L133 using options defined in https://github.com/d2g/dhcp4/blob/master/constants.go

**Comment by f1-outsourcing** [comment]
Yes I would start with the VendorClassIdentifier 60 and maybe the ClientIdentifier 61? Are you telling me I should do this? Is it not nicer to have this available as a default in ipam?

https://github.com/d2g/dhcp4/blob/a1d1b6c41b1ce8a71a5121a9cee31809c4707d9c/constants.go#L107

**Comment by jellonek** [comment]
I'm only pointing the place where this could be added as a contribution, by you, me, or someone other willing to do that later.

**Comment by f1-outsourcing** [comment]
I gave this dhcp a try, why is it accessing a local socket? Does it not have a 'normal' dhcp client request?
CNI_PATH="/usr/libexec/cni/" NETCONFPATH="/etc/mesos-cni" cnitool-0.5.2 add test-dhcp /var/run/netns/testing

error dialing DHCP daemon: dial unix /run/cni/dhcp.sock: connect: no such file or directory

**Comment by f1-outsourcing** [comment]
Hi Piotr,

I have been testing a bit with the ipam dhcp plugins, and even created one myself to get a bit better understanding. 

I assume you are using the socket to communicate with an external dhcp server to retrieve an ip address. You cannot use the namespace interface yet, because it is not created.
In my test dhcpslim plugin, I have added a special parameter that allows you to specify an interface on the host to send the dhcp request via.
What I like about this, is that you have less dependency on your host configuration (do not need to run some daemon there). 
Maybe you can add this option to the default dhcp plugin?

**Comment by jellonek** [comment]
Ok, I'll try to find time for that during next week.
Afair this socket is used to contact from short living part of plugin to a long living process, which is working as a real dhcp client. Will take a look on that later.
