### ISSUE TITLE
Inconsistency in bandwidth calculation

### ISSUE THREAD

**Issue by bboreham** [containernetworking/plugins#392]
Here the third parameter is the 'burst':
https://github.com/containernetworking/plugins/blob/0f19aa2f8d9939b3540c7712929cac79fef87eca/plugins/meta/bandwidth/ifb_creator.go#L131

but on receipt this parameter is named `buffer`:
https://github.com/containernetworking/plugins/blob/0f19aa2f8d9939b3540c7712929cac79fef87eca/plugins/meta/bandwidth/ifb_creator.go#L162

Since we also have a value for 'buffer' at the call site, this is at best confusing and possibly wrong.

**Comment by mars1024** [comment]
Actually these transfer functions are coming from [https://github.com/vishvananda/netlink/blob/ac5f4df047429f3bf1e076eb4053cd44d17f4012/qdisc_linux.go#L658](https://github.com/vishvananda/netlink/blob/ac5f4df047429f3bf1e076eb4053cd44d17f4012/qdisc_linux.go#L658) ... If I have time, I'll take a look at this logic again..
