### ISSUE TITLE
improve MTU assignment and validation

### ISSUE THREAD

**Issue by mars1024** [containernetworking/plugins#393]
Try to create container network through macvlan plugin, but got `Invalid arguments` error from kernel, it is about wrong MTU configuration.
So I open this issue to track the improvement about MTU assignment and validation in different plugins (macvlan, vlan...)

**Comment by squeed** [comment]
cc @s1061123 - you might be interested in this.

**Comment by mars1024** [comment]
> @mars1024 is the issue that the MTU passed to macvlan/vlan in those plugin's config should be validated against the parent/master interface's MTU?

Yes, that's the point.

**Comment by mars1024** [comment]
I'm working on this in my own code base, will pull some requests soon :)

**Comment by mars1024** [comment]
@squeed  Could you help to reopen this?
