### ISSUE TITLE
Separate ipMasq for IPv4 and IPv6

### ISSUE THREAD

**Issue by oszi** [containernetworking/plugins#398]
The `bridge` plugin has an `ipMasq` setting which masquerades traffic from containers. It doesn't really make sense with IPv6 networks but it does it anyway. I propose that it should only apply to IPv4 or there should be another way to specify that I do not want masquerading for IPv6.

For example, `ipMasq: true` would imply `ip6Masq: true` for backwards compatibility but people could set it to false. Of course, one could always set up masquerading manually and ignore this setting so this is a low priority issue.

**Comment by bboreham** [comment]
In a Kubernetes context there is https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/

Would it be cleaner to do it in CNI?

**Comment by oszi** [comment]
I would just change it so that ipMasq would only do IPv4 masquerading. I doubt anyone depends on masquerading IPv6 with this setting.

The chained plugin does sound interesting but we could do the same with firewalld in a breeze, and apparently Kubernetes doesn't even use this at all. How about improving the firewalld (and iptables?) plugins to be capable of masquerading and potentially more?

**Comment by Scrumplex** [comment]
Well I am currently unable to use anything based on CNI, as this ipMasq setting drives me crazy. I recently switched to firewalld and can't find a way to get traffic flowing between the host and my podman containers. Without this option. Problem is that this uses iptables rules which get flushed on the next firewalld reload. Is there an "easy" way of letting firewalld know what to do?
