### ISSUE TITLE
Add dynamic backend for firewall plugin

### ISSUE THREAD

**Issue by mheon** [containernetworking/plugins#402]
Background: This originally spawned from https://github.com/containers/libpod/issues/4260 where a user swapped from the `iptables` backend to the firewall plugin to `firewalld` and ended up resolving his issue. It sounds like this may be a bug elsewhere, but it made me think. The original, unmerged implementation of the firewall plugin dynamically detected if `firewalld` was present and used it if available, falling back to `iptables` if it was not. We don't have a way to do this now - we have to hardcode one or the other, and for things like Podman, which ship on multiple distributions, the default has to be `iptables` for its broad support.

It seems like it would be fairly simple to duplicate the behaviour of the original firewall plugin, selecting between `firewalld` and `iptables` based on which was available, with a new backend (I'm tentatively calling it dynamic). The original Libpod issue may be a bug elsewhere in the `iptables` backend, but it seems like it is preferable to use the firewalld API when it's available - it integrates better with the system firewall.

**Comment by dcbw** [comment]
@mheon would you be willing to do a patch for this one?
