### ISSUE TITLE
Static plugin: Setting gateway when using 'ips' RuntimeConfig

### ISSUE THREAD

**Issue by Elegant996** [containernetworking/plugins#406]
@s1061123 

Would it be possible add an optional RuntimeConfig parameter that would allow us to set the interface gateway? The `gateway` parameter would apply to all `ips` defined in RuntimeConfig but would not affect those defined using the `addresses` array.

The reason for this change is to allow for plugins such as `sbr` to be able to create a default route to the gateway on new routing tables. Currently, the default route is skipped if the gateway is not defined.

What are your thoughts?

Thanks!

**Comment by s1061123** [comment]
@Elegant996 it could be, but I don't think we should have because of not so major use-case. In addition, static plugin only assigns 'static ip address' and it does not provide flexible way to assign ip address. 

Above use case, you may need another plugin with different concept.

**Comment by Elegant996** [comment]
@s1061123 was using `host-local` ipam as reference. Perhaps this may be more suited for `tuning` or would it be best if this was just an ordinary option outside of RuntimeConfig and be added to `sbr` itself? Thanks!

**Comment by s1061123** [comment]
`runtimeConfig` is the parameter which the CNI runtime (e.g. kubelet in case of kubernetes) puts. So first we may need to come up with such scenario.
