### ISSUE TITLE
Do we need a unified MAC generator for container interface?

### ISSUE THREAD

**Issue by mars1024** [containernetworking/plugins#407]
Now I'm working on a tool to defend MAC flooding attack from container, I want to implement this based on ebtables on linux bridge.
But because of irregular MAC addresses generated by kernel, there will be a large mount of ebtables rules.
So I think maybe we need a unified MAC generator for our L2 CNI plugins(macvlan, vlan, ipvlan, etc) to generate regular MAC addresses(with same prefix) based on a certain rule, this will help us to recognize/locate the MACs of the container interfaces with a "regular" expression.

**Comment by mars1024** [comment]
MAC "regular" expression is like address/mac:
```
       -s, --source [!] address[/mask]
              The source MAC address. Both mask and address are written as 6 hexadecimal numbers separated by colons. Alternatively one can  specify  Uni‐
              cast, Multicast, Broadcast or BGA (Bridge Group Address):
              Unicast=00:00:00:00:00:00/01:00:00:00:00:00, Multicast=01:00:00:00:00:00/01:00:00:00:00:00, Broadcast=ff:ff:ff:ff:ff:ff/ff:ff:ff:ff:ff:ff or
              BGA=01:80:c2:00:00:00/ff:ff:ff:ff:ff:ff.  Note that a broadcast address will also match the multicast specification. The flag  --src  is  an
              alias for this option.
```

**Comment by mars1024** [comment]
TODOs
- [ ] hwaddr utility package
- [ ] bring this feature to plugins as a config switch

**Comment by matthewdupre** [comment]
I don't really understand exactly which flooding attack you're trying to prevent here?

It's not obvious to me why putting all the containers in a common MAC prefix helps you constrain the rules about them - I can imagine it would help prevent attacks on things that aren't containers, but containers need to be protected from other local containers as well?

**Comment by mars1024** [comment]
> I don't really understand exactly which flooding attack you're trying to prevent here?
> 
> It's not obvious to me why putting all the containers in a common MAC prefix helps you constrain the rules about them - I can imagine it would help prevent attacks on things that aren't containers, but containers need to be protected from other local containers as well?
> 
> If you could link me to a description of the attack that might help me understand, thanks.

Yes, I think you're right, actually what I'm doing is dropping all arp packets from containers and let node be the arp proxy for all the containers on a linuxbridge through ebtable rules so that there will not be ARP attack any more, and the same prefix of MAC addresses will not reduce the number of ebtable rules, because we need both IP and MAC (even container veth peer interface name) as arguments of ebtable rules, so we can not squash several rules into one.

So I think this PR will not help us, but only solve two questions, the MAC generator support dual stack and CNI OUI(such like VMware has a unified CNI OUI for its virtual machines), this PR is better to have but not necessary to have, it's up to you.
