### ISSUE TITLE
A home for netlink within CNI?

### ISSUE THREAD

**Issue by caniszczyk** [containernetworking/plugins#41]
I spoke with @vishvananda and he's interested in finding a home + growing the contributor base for his netlink (https://github.com/vishvananda/netlink) library which CNI uses along with other networking related projects.

Is there any interest in the CNI maintainer-ship?

At the moment, I don't think CNI has a clear process on accepting new projects unless I'm mistaken, this could be an exercise in defining one.

**Comment by feiskyer** [comment]
+1 for this. Most plugins are depending on it.

**Comment by rkamudhan** [comment]
+1

**Comment by caniszczyk** [comment]
@dcbw @bboreham @tomdee, thoughts here?

**Comment by bboreham** [comment]
The maintainers' meeting is every Wednesday at 8am SF time, so we have not discussed yet.

**Comment by caniszczyk** [comment]
@bboreham how about we have @vishvananda present at the next meeting? 23rd?

**Comment by bboreham** [comment]
@caniszczyk I should have updated earlier: we discussed on 26th July and concluded "Somewhat positive, want @vishvananda to come up with a plan for bringing more maintainers to the project"

Next meeting will be the 30th due to vacations; very happy for @vishvananda to present.

**Comment by caniszczyk** [comment]
Now that CNI has Governance in place via https://github.com/containernetworking/cni/blob/master/GOVERNANCE.md we should chat about holding a vote for netlink?

cc: @containernetworking/cni-maintainers

**Comment by bboreham** [comment]
We'd need a proposal to vote on.

**Comment by leodotcloud** [comment]
+1

**Comment by bboreham** [comment]
@vishvananda joined us at the CNI maintainers' meeting today; we seem to have a good basis to move forward.

**Comment by caniszczyk** [comment]
Awesome!

**Comment by zhouhaibing089** [comment]
And nothing happened?
