### ISSUE TITLE
Recent commit caused coreDNS pods pending

### ISSUE THREAD

**Issue by Funky-Hamster** [containernetworking/plugins#410]
Hi, I used the same way to deploy some Kubernetes clusters by running the installing script. However, today the coreDNS pods are pending and cannot apply Calico. There's no logs in the pending coreDNS pods and the error of applying Calico is "unable to read URL "https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/rbac.yaml", server reported 403 Proxy Unacknowledged, status code=403".

Executing Command: kubectl get pods --all-namespaces
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE
kube-system   coredns-6dcc67dcbc-82rm9          0/1     Pending   0          2m24s
kube-system   coredns-6dcc67dcbc-fbnnr          0/1     Pending   0          2m24s

**Comment by bboreham** [comment]
Sounds like you have a http proxy in your environment blocking the request.
Either way, nothing to do with this project.
