### ISSUE TITLE
bandwidth not support macvlan

### ISSUE THREAD

**Issue by zcc35357949** [containernetworking/plugins#413]
hello, friends! 
I test the bandwidth plugin with flannel or calico successfully. But it doesn't seem to work with macvlan. 
Does it create the tc rules only in host namespace ?

**Comment by zcc35357949** [comment]
I think we need to create qdisc in container network namespace when we use macvlan network.      
What do you think?

**Comment by squeed** [comment]
@zcc35357949 hmm - how might this look?

It might make sense for macvlan to implement the bandwidth capability directly

**Comment by hrax0214** [comment]
Looking forward to this feature
