### ISSUE TITLE
Portmap integration test forwards a TCP port on ipv4 is flaky

### ISSUE THREAD

**Issue by aojea** [containernetworking/plugins#422]
It failing randomly and with different causes.

After adding some debug commands I could observe that sometimes the test is running in the root namespace and other inside a namespace with the loopback interface down .

Others is not able to find the iptables rules but the previous dump shows that

https://travis-ci.org/containernetworking/plugins/jobs/623633319?utm_medium=notification&utm_source=github_status

**Comment by squeed** [comment]
Uh oh, that means that we're somehow failing leave the test namespace. Can you try and find out how?

**Comment by aojea** [comment]
fixed by https://github.com/containernetworking/plugins/pull/421
