### ISSUE TITLE
bridge: communication between pods on same node doesn't work

### ISSUE THREAD

**Issue by weibeld** [containernetworking/plugins#430]
I'm using the CNI plugins installed by kubeadm, which is [CNI plugins 0.7.5](https://github.com/containernetworking/plugins/releases/tag/v0.7.5).

This is the configuration file:

```json
{
   "cniVersion": "0.3.1",
   "name": "my-bridge-network",
   "type": "bridge",
   "isDefaultGateway": true,
   "ipMasq": true,
   "ipam": {
      "type": "host-local",
      "subnet": "200.200.0.0/24"
   }
}
```

After installing the plugin, pinging a pod on the same node from another pod doesn't work. The reason is the `DROP` default action in the `FORWARD` netfilter chain:

```bash
sudo iptables -S FORWARD
-P FORWARD DROP
# ...
```

This is evaluated for packets passing through the bridge _before_ the `POSTROUTING` chain which is customised by the [`setupIPMasq`](https://github.com/containernetworking/plugins/blob/655116585396cc26ca973db2d5daef66d821ad90/pkg/ip/ipmasq_linux.go#L26) library function, which is used by the bridge plugin. So, packets from one pod to another pod on the same node are dropped before they even reach the `POSTROUTING` chain.

If I just set the default for the `FORWARD` chain to `ACCEPT`, the communication works:

```bash
sudo iptables -P FORWARD ACCEPT
```

The node operating system is Ubuntu 18.04 LTS, kernel version is `5.0.0-1026-gcp`.

**Comment by squeed** [comment]
Yup, this is definitely a problem - we solved it with the `firewall` plugin, which will add ALLOW rules for containers as they come up. Can you upgrade to plugins v8.x and give that a try?

**Comment by weibeld** [comment]
Sure, will give it a try when i have time.

**Comment by alexellis** [comment]
Is the firewall plugin necessary for container-to-container communication then, with the bridge plugin? @bboreham maybe there could be a note about this in the README? We ran into it too with [faas-containerd](https://github.com/alexellis/faas-containerd)

**Comment by rata** [comment]
Heh, I've written a PR for the bridge plugin to handle the IPForward too, but now I see this, tested adding the firewall plugin and I can confirm it works fine for me.

I don't like to have the rules scales on the number of containers (we can just accept on the bridge interface), but I see *could* be hard to tackle if we support more generic use cases in the same network/interface (not sure it is possible, though).
