### ISSUE TITLE
bridge:get dns config from /etc/cni/net.d default config, not from ipam plugins

### ISSUE THREAD

**Issue by jamin-hon** [containernetworking/plugins#431]
Referring to ducuments, bridge plugins does not contain dns config which ipam host-local and static plugins does. 
But i found that bridge get dns config from /etc/cni/net.d original config, not from ipam plugins by reading and testing the source code.

**Comment by davdiv** [comment]
Indeed, I came across the same issue:
https://github.com/containernetworking/plugins/blob/48a97a7ad16cb839d4871cd493faca13129737ca/plugins/main/bridge/bridge.go#L568
The `DNS` in the result is copied from `n`, which is the bridge configuration (and nothing is mentioned in the following page regarding the possibility to pass a `dns` field: https://www.cni.dev/plugins/main/bridge/).
It should be copied from `ipamResult.DNS`, according to the documentation (https://www.cni.dev/plugins/ipam/host-local/). As a result, `resolvConf` in `host-local` configuration is mistakenly ignored when used with bridge.
