### ISSUE TITLE
How to push CNI plugins to https://storage.googleapis.com/kubernetes-release/network-plugins

### ISSUE THREAD

**Issue by huchengze** [containernetworking/plugins#436]
To fix the step 4 of this [issue](https://github.com/kubernetes/kubernetes/issues/87056), I need to push the mips64le CNI plugins to 
https:// storage.googleapis.com/kubernetes-release/network-plugins/cni-plugins-mips64le-v0.8.4.tgz.

I see that the mips64le CNI plugins are already released in
https://github.com/containernetworking/plugins/releases/download/v0.8.4/cni-plugins-linux-mips64le-v0.8.4.tgz

Will these plugins regularly pushed to _https:// storage.googleapis.com/kubernetes-release/network-plugins_?

**Comment by cadmuxe** [comment]
I am also looking the release process, unfortunately we don't have a release pipeline/process for this yet. 
Looks like we should at least have the following stuff:
1. Documents about the release process. 
2. CI to push the releases to kubernetes-release/network-plugins
