### ISSUE TITLE
Examine cases where plugins return error on DEL

### ISSUE THREAD

**Issue by bboreham** [containernetworking/plugins#441]
#438 appears to have been caused by a typo where the code was special-casing 'not found', but in practice it is hardly ever a good idea to return an error from DEL because runtimes like Kubernetes will simply repeat the operation forever.

This issue is to remind us to review all error returns from DEL in the plugins in this repo.

**Comment by mars1024** [comment]
Willing to do this :)  Idempotency of DEL should be concerned.

**Comment by mars1024** [comment]
BTW, CNI DEL should be designed for an absolute clean-up, even again and again.

**Comment by mars1024** [comment]
TODOs

- [ ] #445 pkg/ip: use type cast instead of untrusty error message
