### ISSUE TITLE
Release process improvements request from Kubernetes project

### ISSUE THREAD

**Issue by justaugustus** [containernetworking/plugins#446]
Hey CNI plugins maintainers,

As you're already familiar, the Kubernetes project produces `kubernetes-cni` deb/rpm packages.
We're working on making improvements to our packaging processes and to assist in this, we're asking for the following from this project:

- [x] (https://github.com/containernetworking/plugins/pull/454, https://github.com/containernetworking/cni/pull/752) Update repo owners/maintainers (usernames and email addresses)
- [x] Make decision on whether to dual-publish release artifacts (GitHub + Kubernetes GCS) or just to Kubernetes GCS (`gs://k8s-artifacts-cni/release/`)
  - Planning to dual-publish (ref: https://github.com/containernetworking/plugins/issues/446#issuecomment-588309522)
- [ ] Update release scripts to support publishing to GCS
- [ ] Update release documentation

This is a carry of some of the tasks listed in https://github.com/kubernetes/sig-release/issues/245, copied over so we can track in both projects.

ref: https://github.com/kubernetes/sig-release/issues/245, https://github.com/containernetworking/plugins/issues/436, https://github.com/kubernetes/kubernetes/issues/87228, https://github.com/containernetworking/plugins/issues/285

cc: @dcbw @squeed @bboreham @jellonek @thockin @tpepper @calebamiles @hoegaarden @saschagrunert @cpanato

**Comment by bboreham** [comment]
We didn't get to this in today's maintainers meeting; next one is in a week.
Can you give some guidance on timelines when you need things to change or decisions to be made?

**Comment by justaugustus** [comment]
@bboreham -- The sooner we can attack this for the 1.18 cycle, the better.

> - Update repo owners/maintainers (usernames and email addresses)

This one is most important to me right now, to ensure that the IAM group for GCP is up-to-date: https://github.com/kubernetes/k8s.io/blob/e40c2ef329e54539440667fd7bf5a68c115c1db2/groups/groups.yaml#L291-L300

> - Update release documentation

This is probably the next one I'd want to see.

**Comment by bboreham** [comment]
> Update repo owners/maintainers (usernames and email addresses)

I suspect I don't understand your ask here.  The `OWNERS.md` file in this repo is up to date; is that what you wanted?

**Comment by justaugustus** [comment]
> I suspect I don't understand your ask here. The `OWNERS.md` file in this repo is up to date; is that what you wanted?

@bboreham -- Email addresses are definitely out of date. I see a few CoreOS ones in there.

**Comment by bboreham** [comment]
OK, the CoreOS addresses will still work, but we'll update them. #454 

As for the rest, we discussed at the maintainers meeting and we are sorely lacking in context. I think [this comment](https://github.com/kubernetes/kubernetes/issues/87228#issuecomment-580330485) is probably important:
> CNI plugins will now be retrieved from https://storage.googleapis.com/k8s-artifacts-cni/release/, which is a GCS bucket with shared control between CNI plugin maintainers and the Kubernetes Release Engineering subproject.

So, in that light, we can make some sense of:

>  Update release scripts to support publishing to GCS

Is there any tooling or prior art that we can build on?

As for:

> Make decision on whether to dual-publish release artifacts (GitHub + Kubernetes GCS) or just to Kubernetes GCS

The CNI project is independent of Kubernetes and is used by other container orchestrators.  So that leaves dual-publish.

**Comment by dcbw** [comment]
update coreos emails:
https://github.com/containernetworking/plugins/pull/454
https://github.com/containernetworking/cni/pull/752

**Comment by dcbw** [comment]
> @bboreham -- The sooner we can attack this for the 1.18 cycle, the better.
> 
> > * Update repo owners/maintainers (usernames and email addresses)
> 
> This one is most important to me right now, to ensure that the IAM group for GCP is up-to-date: https://github.com/kubernetes/k8s.io/blob/e40c2ef329e54539440667fd7bf5a68c115c1db2/groups/groups.yaml#L291-L300

@justaugustus are you suggesting that people from the CNI maintainers/owners file would also be added to this list? I think the current 3-person list is too short given the load on at least Tim and I...

**Comment by justaugustus** [comment]
> As for:
> 
> > Make decision on whether to dual-publish release artifacts (GitHub + Kubernetes GCS) or just to Kubernetes GCS
> 
> The CNI project is independent of Kubernetes and is used by other container orchestrators. So that leaves dual-publish.

Sounds good!

> So, in that light, we can make some sense of:
> 
> > Update release scripts to support publishing to GCS
> 
> Is there any tooling or prior art that we can build on?

@bboreham -- Nothing at the moment. 
Since we're planning to dual-publish, I imagine a simple shell script in `k/release` that either Kubernetes Release Managers or CNI maintainers can run after a new plugins release happens.

> @justaugustus are you suggesting that people from the CNI maintainers/owners file would also be added to this list? I think the current 3-person list is too short given the load on at least Tim and I...

@dcbw -- Correct. I've sent a [PR](https://github.com/kubernetes/k8s.io/pull/591) to update `k8s-infra-push-cni@kubernetes.io` to include:
- CNI maintainers
- SIG Network Chairs
- Kubernetes Release Managers
