### ISSUE TITLE
How to fix IP for container ？

### ISSUE THREAD

**Issue by X-Mars** [containernetworking/plugins#448]
Dear All,
     I want to match the IP with the deploy name, Deploy's IP will not change even if the container is rebuilt.
     plugins:  macvlan, host-local
     I want to rewrite host-local and cache Deploy relationship with IP, but I can't get Pod Name or Deploy Name in host-local main.go .
     Help me ,please

X-Mars

**Comment by mccv1r0** [comment]
Do you really care about the name used or do you just want this specific container image to always have the same IP?  If it's just the same IP each time you could use either static IPAM or host-local with the IP argument.

https://github.com/containernetworking/plugins/tree/master/plugins/ipam/host-local#supported-arguments

**Comment by X-Mars** [comment]
I finished it
Host-local can get Pod Name when start pod in kuernetes.
Thank you My friend.
Best wishes for you

X-Mars
