### ISSUE TITLE
Host-local should support disjoint sets of ranges.

### ISSUE THREAD

**Issue by selvakumarnms** [containernetworking/plugins#45]
Hi ,
I was testing the multiple ranges support for the IP and looks like it tries to get the IP from all the subnets at a time rather than one by one range.

Is this the expected behaviour ?

echo '{
"cniVersion": "0.3.1",
"name": "examplenet",
"ipam": {
"type": "host-local",
"ranges": [{
"subnet": "10.10.10.0/24",
"rangeStart": "10.10.10.20",
"rangeEnd": "10.10.10.22"

}, {
"subnet": "20.20.20.0/24",
"rangeStart": "20.20.20.20",
"rangeEnd": "20.20.20.21"

}],
"dataDir": "/tmp/cni-example"
}
}' | CNI_COMMAND=ADD CNI_CONTAINERID=example CNI_NETNS=/dev/null CNI_IFNAME=dummy0 CNI_PATH=. ./host-local

**Comment by selvakumarnms** [comment]
My expectation would be first 10.10.10. network should be exhausted and then it should give ip from 20.20.20.20 network rather than at a time allocating ip

**Comment by squeed** [comment]
This is the intended behavior as written. The initial goal was to support dual-stack networks, so the plugin treats each range independently.

I haven't really seen the need for a single "pool" of disparate ranges - can you provide a use-case?

**Comment by dcbw** [comment]
@squeed we actually have one with OpenShift, sometimes the size of the subnet that people can use isn't that large so they want to use a couple on a given node.  Like say they use 172.16.x.x but there are some legacy systems that use some /24s, etc.

**Comment by squeed** [comment]
Thought for a bit about the configuration format. Couldn't really come up with anything particularly clever:

```json
{
    "ipam": {
        "type": "host-local",
        "ranges": [
            [
                        {"subnet": "10.0.0.0/24"},
                        {"subnet": "172.16.5.0/24"}
            ],
            [
                        {"subnet": "2001:db8:96:abd::/64"}
            ]
        ]
    }
}
```

I don't love it, but it's OK. One question is if we're going to want to add some sort of "pool-level" property. It will add a lot of verbosity though.

**Comment by squeed** [comment]
Hah, @dcbw, this will break our cute last_allocated_ip filename prefix scheme (we used an encoding of the first IP).

I might switch it back to index-based.
