### ISSUE TITLE
Isolating containers on separate bridge networks

### ISSUE THREAD

**Issue by aparhatus** [containernetworking/plugins#474]
Given two containers on separate bridge networks (see configs below), it appears that the containers are able to communicate with each other via their respective IPs. In other words, container 1 (net1) can access a service running on container 2 (net2) via its IP 10.89.1.2.

Is there any way to isolate these containers, so that they can communicate with the host, but not to each other unless they are in the same network? In practice, I'd like to restrict container 1's access to a web service on container 2, unless it goes through a secure reverse proxy on the host, like everyone else is required to.

I realise this could probably be achieved by adding the right firewall rules, but the CNI plugins already appear to add some of their own and I'm not sure what the correct approach is here - can it be solved solely through the CNI configs?

**net1 config**
```
{
   "cniVersion": "0.4.0",
   "name": "net1",
   "plugins": [
      {
         "type": "bridge",
         "bridge": "cni-podman1",
         "isGateway": true,
         "ipMasq": true,
         "ipam": {
            "type": "host-local",
            "routes": [
               {
                  "dst": "0.0.0.0/0"
               }
            ],
            "ranges": [
               [
                  {
                     "subnet": "10.89.0.0/24",
                     "gateway": "10.89.0.1"
                  }
               ]
            ]
         }
      },
      {
         "type": "portmap",
         "capabilities": {
            "portMappings": true
         }
      },
      {
         "type": "firewall",
         "backend": ""
      },
      {
         "type": "dnsname",
         "domainName": "dns.podman"
      }
   ]
}
```
**net2 config**
```
{
   "cniVersion": "0.4.0",
   "name": "net2",
   "plugins": [
      {
         "type": "bridge",
         "bridge": "cni-podman2",
         "isGateway": true,
         "ipMasq": true,
         "ipam": {
            "type": "host-local",
            "routes": [
               {
                  "dst": "0.0.0.0/0"
               }
            ],
            "ranges": [
               [
                  {
                     "subnet": "10.89.1.0/24",
                     "gateway": "10.89.1.1"
                  }
               ]
            ]
         }
      },
      {
         "type": "portmap",
         "capabilities": {
            "portMappings": true
         }
      },
      {
         "type": "firewall",
         "backend": ""
      },
      {
         "type": "dnsname",
         "domainName": "dns.podman"
      }
   ]
}
```

**Comment by bboreham** [comment]
Sorry for delay in responding.

Given both networks have an address on the host, Linux will route packets freely between them as you have discovered.

There isn't any plugin in this repo to achieve the result you asked for.  It does appear to need quite specific firewall rules.

I suspect that by masquerading you lose the original source IP, so you would need to block based on bridge device.

**Comment by aparhatus** [comment]
Thank you for the clarification @bboreham. I ended up writing a hackish plugin to add the necessary firewall rules in the FORWARD chain, dropping packets based on source and destination IPs. Something along these lines:

```
$ sudo firewall-cmd --direct --get-all-rules
ipv4 filter FORWARD 0 -s 10.88.4.7/24 -d 10.88.4.7/32 -j ACCEPT
ipv4 filter FORWARD 1 -s 10.0.0.0/8 -d 10.88.4.7/32 -j DROP
```

Appears to do the job, though I do have a very limited understanding of the networking stack. My setup is very basic though.
