### ISSUE TITLE
SBR: IPv6 fails to parse IPv6 addrs.

### ISSUE THREAD

**Issue by nysan** [containernetworking/plugins#478]
SBR plugin mistakenly thinks IPv6 address is 64 bit.
Consequence of this is that SBR plugin "ip rule" tables for IPv6 addresses catches _all_
src ip:s. Not only src ip.

Changing CIDRMask from 64 to 128 fixes the issue.
Above changes fixes the issue for me.

Mvh,
David

**Comment by uablrek** [comment]
Is it sufficient to change 64 -> 128 in these 2 lines?

https://github.com/containernetworking/plugins/blob/5af9ff493e60ddda7b6d75a26ff3ba635c7debfb/plugins/meta/sbr/main.go#L240

https://github.com/containernetworking/plugins/blob/5af9ff493e60ddda7b6d75a26ff3ba635c7debfb/plugins/meta/sbr/main.go#L261

**Comment by nysan** [comment]
Yes

**Comment by nysan** [comment]
It probably would not hurt to add an IPv6 testcase as well. To guard this functionality

**Comment by nysan** [comment]
Without this fix:
    --
    root@hello-hello-world-6dbb4d9b79-667g4:/# ip rule
    0:      from all lookup local
    32765:  from 172.24.10.200 lookup 100
    32766:  from all lookup main
    32767:  from all lookup default
    root@hello-hello-world-6dbb4d9b79-667g4:/# ip -6  rule
    0:      from all lookup local
    32765:  from all lookup 100
    32766:  from all lookup main

    With this fix:
    --
    root@hello-hello-world-6dbb4d9b79-667g4:/# ip rule
    0:      from all lookup local
    32765:  from 172.24.10.200 lookup 100
    32766:  from all lookup main
    32767:  from all lookup default
    root@hello-hello-world-6dbb4d9b79-667g4:/# ip -6  rule
    0:      from all lookup local
    32765:  from f80:ffff:0:1ff::1 lookup 100
    32766:  from all lookup main
