### ISSUE TITLE
The CNI pugins v0.6.0 rc1 losing portmap plugin

### ISSUE THREAD

**Issue by gyliu513** [containernetworking/plugins#48]
```
wget https://github.com/containernetworking/cni/releases/download/v0.3.0/cni-v0.3.0.tgz
tar -zxvf cni-v0.3.0.tgz
```

There is no `portmap` plugin.

**Comment by gyliu513** [comment]
I got it from https://github.com/projectcalico/cni-plugin/releases/tag/v1.9.1 , why not packge it in CNI plugin tar ball?

**Comment by squeed** [comment]
There is no portmap in v0.3.0, because it didn't exist until 0.6. It's also in the plugins release, not the cni release.
