### ISSUE TITLE
portmap plugin: add rule to drop off-box 127.0.0.1 packets

### ISSUE THREAD

**Issue by bboreham** [containernetworking/plugins#481]
As reported in https://github.com/kubernetes/kubernetes/issues/90259, because of a [setting that portmap uses](https://github.com/containernetworking/plugins/blob/5af9ff493e60ddda7b6d75a26ff3ba635c7debfb/plugins/meta/portmap/portmap.go#L91),  Linux will accept packets from off-box destined for 127.0.0.1.

In the maintainers meeting we thought it should be possible to add a rule as follows:
 - If the destination is 127.0.0.1 and the packet comes from a non-local address, drop.

Perhaps this would also work:
 - If the destination is 127.0.0.1 and the source address is not 127.0.0.1, drop.

**Comment by EdDev** [comment]
> If the destination is 127.0.0.1 and the source address is not 127.0.0.1, drop.

Is there a mechanism that protects against traffic arriving with 127.0.0.1 as the source?
If there is none, then such a traffic may arrive and present unidirectional security concerns.

**Comment by bboreham** [comment]
Should be dropped by reverse path filter. 
But also we’re generally talking about TCP sockets which need bidirectional comms.
