### ISSUE TITLE
host-local  generate file  with dos format

### ISSUE THREAD

**Issue by hongli-my** [containernetworking/plugins#483]
![image](https://user-images.githubusercontent.com/8597823/81685024-38595e00-948a-11ea-92c4-2c828b82eb14.png)

![image](https://user-images.githubusercontent.com/8597823/81685053-47401080-948a-11ea-92ba-ede5af758cb4.png)

if I operate this file, shoule use dos2unix to change it, why  this foramt ?

**Comment by jellonek** [comment]
What's the problem with such format?
Could you elaborate more why you want to operate on this file, while it's supposed to be implementation detail, holding internal host-local state?
Please provide a wider context.
