### ISSUE TITLE
Enable generating random ports with host port mapping

### ISSUE THREAD

**Issue by gyliu513** [containernetworking/plugins#49]
This is a problem that I found when testing https://github.com/projectcalico/k8s-policy/issues/109 . The problem is that when I use `hostport` mapping feature in calico, I was always need to specify pods `hostPort` as following in `ports` section.

```
root@k8s001:~/calico2.4# cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-host
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx-host
    ports:
    - containerPort: 80
      hostPort: 80
  restartPolicy: Always
root@k8s001:~/calico2.4# kubectl create -f ./pod.yaml
pod "nginx-host" created
root@k8s001:~/calico2.4# kubectl get pods -owide
NAME                      READY     STATUS    RESTARTS   AGE       IP                NODE
nginx-host                1/1       Running   0          9s        192.168.124.143   k8s004
```

The problem is that if one node start two such pods, only one pod can be started and another pod will be pending always as it cannot get the same port again.

Enable `host port mapping` can generate the host port randomly so that end user will not need to specify the host port.

**Comment by squeed** [comment]
Generating the actual port mappings is the task of the orchestrator, be it kubernetes, cloudfoundry, or manual tracking (with rkt). The portmap plugin doesn't have the ability to generate configuration.
