### ISSUE TITLE
Support "mac" capability arg in all reasonable plugins

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#492]
There is a 'mac' capability arg, but it's only consumed by tuning and macvlan. We really should support it in every reasonable interface plugin.

**Comment by MikeZappa87** [comment]
The list to add the mac cap is: ipvlan,ptp and vlan? In the case where two assignable interfaces exist such as ptp should only the veth inside the network namespace have the mac set? Should this be a single PR or a PR per plugin?

**Comment by alexanderniebuhr** [comment]
@squeed coming back to this, since I have an issue with bridge right now. Did the [pr](https://github.com/containernetworking/plugins/pull/480) end-up ported to any other plugins?
