### ISSUE TITLE
Tuning Plugin: Revert Values on Delete

### ISSUE THREAD

**Issue by killianmuldoon** [containernetworking/plugins#493]
Tuning plugin sets the MTU of interfaces, but it doesn't reset to the previous value on reset. We've seen issues with this where some containers looking for the same type of interface configure MTU while other networks assume default MTU at 1500.

The CmdDel method in the tuning CNI is a TODO with:
>	// TODO: the settings are not reverted to the previous values. Reverting the
	// settings is not useful when the whole container goes away but it could be
	// useful in scenarios where plugins are added and removed at runtime.

Is there a plan to implement reverting settings with the tuning plugin? Could we implement the MTU revert by itself or would there need to be a broader reset function for other settings touched by the tuning cni?

**Comment by squeed** [comment]
It's tough, because the tuning plugin wouldn't necessarily know what the MTU was at the beginning.

**Comment by squeed** [comment]
Can you outline the sort of "reset" scenario you're talking about? Generally, tuning only touches the container-side of the network, so I would expect any customizations to be moot when the interface is deleted.

I suppose this could affect host-device? But that strikes me as odd that you'd want a different MTU in vs. outside the container.

**Comment by killianmuldoon** [comment]
The issue we're seeing is with getting an unexpected MTU where it's not set explicitly. 

i.e. Workload 1 requires jumbo frame MTU of 9000, tuning plugin sets it, and it receives the correctly configured interface. Once it finishes its work the container is deleted. 

Workload 2 looks for the same kind of interface, but assumes a default MTU i.e. 1500. It picks up the interface, but then hits an issue because the MTU is actually at 9000.

**Comment by killianmuldoon** [comment]
@squeed do you think this is worth pursuing in a PR?

**Comment by dcbw** [comment]
@killianmuldoon sure, lets see what that PR looks like.
