### ISSUE TITLE
why is the route for the device moved from main table in the sbr plugin?

### ISSUE THREAD

**Issue by blackgold** [containernetworking/plugins#496]
"It moves every existing route on the device to the new table." I see following in [readme](https://github.com/containernetworking/plugins/tree/master/plugins/meta/sbr#usage)

Any specific reason why its done?

**Comment by bboreham** [comment]
@plwhite you contributed this - can you comment?

**Comment by plwhite** [comment]
Suppose you have a pod that gets IP addresses A and B. With source based routing, you want to have two sets or routes used, depending on whether the source is A or B. The only way to do this is to put the routes that go with A into one table, and the routes that go into B into another, then configure a rule to pick which table based on source IP.

Given that the CNI plugins that set up routes for A and B know nothing about source based routing in general, they put the routes into the default table. This plugin then comes along afterwards and moves them to the correct table instead.

**Comment by bboreham** [comment]
Thanks @plwhite !  

I shall assume this is enough to close the issue; @blackgold please let us know if not.

**Comment by matthewdupre** [comment]
Source based routing is used to meet quite specific networking requirements with multiple interfaces.  You'd know if you needed it.

**Comment by blackgold** [comment]
If the route is not removed from main table then there is no need to specify interface information when using tools like ping or curl.
So I was wondering is there any specific reason for removing the route information from main table.
