### ISSUE TITLE
Windows: Support Container hostPort

### ISSUE THREAD

**Issue by markmandel** [containernetworking/plugins#497]
I work on https://agones.dev, and we're attempting to support dedicated game servers on Windows, which is a pretty large use case for us, and we require container hostPort support to make our platform work (unfortunately NodePort, or any kind of service is a non starter for a variety of reasons) - without it, we are blocked on this workload.

Additional context:
* Kubernetes Issue: https://github.com/kubernetes/kubernetes/issues/90116
* Agones Issue: https://github.com/googleforgames/agones/issues/54
* Slack thread: https://kubernetes.slack.com/archives/C0SJ4AFB7/p1591381173181100

**Comment by cwdsuzhou** [comment]
see kubernetes/kubernetes#90116

I would send a PR later.
