### ISSUE TITLE
host-local IP may leak

### ISSUE THREAD

**Issue by chendotjs** [containernetworking/plugins#498]
On one of our online servers, we found that there were many empty IP files created by host-local and the net range is exhausted.  
 
It may happen when host-local creates an empty file successfully, but fails to write string into it and further fails to remove it. When kubelet reties and retries to ensure a new container, this process is repeated so dozens of empty files are created. 
https://github.com/containernetworking/plugins/blob/1fb9793607361bc8ae032a12964c67e7f2b92079/plugins/ipam/host-local/backend/disk/backend.go#L62-L73

We should check if IP file is empty to determine whether an IP can be allocated. This not only prevents exhausting all free IPs, but also helps to recover leaked IP files.

**Comment by bboreham** [comment]
This sounds to me like a bug on the `ADD` side - the plugin shouldn't leave an empty file lying around under normal operating conditions.

On the other hand, it is possible for things to get dropped. There should be a reconcilliation of IPAM entries to containers, but CNI doesn't have any way to know what the caller meant by container ID (is it a Rkt ID? Docker ID?).  One for CNI V2.
