### ISSUE TITLE
Where can I find the log of the plugins, such as bandwidth plugin?

### ISSUE THREAD

**Issue by qibobo** [containernetworking/plugins#502]

**Comment by bboreham** [comment]
I couldn't see any attempt to log from the bandwidth plugin.

Some messages may go to stderr which would be inherited from the calling process.
E.g. when using Kubernetes the caller is kubelet, so look in its log.

**Comment by dcbw** [comment]
Another example, if the caller is CRIO, look in the CRIO service log.
