### ISSUE TITLE
Document the CNI-ADMIN chain in firewall plugin README

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [containernetworking/plugins#504]
## Background
We'd like to leverage the `firewall` plugin with the `iptables` backend and add a rule to block traffic from the containers to a specific IP. The firewall plugin creates the `CNI-ADMIN` chain. 

Is that chain meant for extension by us ? Could we safely use it to add a REJECT rule which all containers would be subject to ?

We also noticed the `iptablesAdminChainName`  in [code](https://github.com/containernetworking/plugins/blob/master/plugins/meta/firewall/firewall.go#L41-L43),  which isn't documented the README but seems to suggest that its meant for consumers of CNI to leverage.

If confirmed, I can add a PR to update the README.

**Comment by dcbw** [comment]
@xtreme-sameer-vohra yes, it is intended as a user-controlled chain that all traffic passes through before the firewall plugin's rules. That should be documented better.

**Comment by xtreme-sameer-vohra** [comment]
Thanks for the confirmation
