### ISSUE TITLE
bridge: Container<-->Container traffic bypasses host gateway

### ISSUE THREAD

**Issue by danopia** [containernetworking/plugins#508]
Hello, I'm using the bridge plugin to set up some Podman containers, and I want to customize container traffic using the host kernel. To be specific I'm replicating Kubernetes ClusterIPs using nftables. However I'm running into some difficulty performing the necessary Destination NAT when both containers are on the same bridge CNI. It seems like the netns routing allows pods to talk directly to each other without the host kernel being able to apply its conntracking context. If pod B knows the traffic came from pod A, it just responds directly, which results in invalid directly.

Example CNI

```json
{
  "cniVersion": "0.4.0",
  "name": "bridge",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cni-bridge",
      "isGateway": true,
      "ipam": {
        "type": "host-local",
        "routes": [ { "dst": "0.0.0.0/0" } ],
        "ranges": [
          [ { "subnet": "10.10.0.0/25", "gateway": "10.10.0.1" } ]
        ]
      }
    },
...}
```

The resulting routes look like:

```
fdf6eff03a76:/# ip route
default via 10.10.0.1 dev eth0
10.10.0.0/25 dev eth0 scope link  src 10.10.0.62

fdf6eff03a76:/# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.10.0.1       0.0.0.0         UG    0      0        0 eth0
10.10.0.0       *               255.255.255.128 U     0      0        0 eth0
```

For comparison, here's how a normal Kubernetes pod is configured:

```
irc-client-0:/# ip route
default via 10.8.0.1 dev eth0 
10.8.0.0/25 via 10.8.0.1 dev eth0  src 10.8.0.4 
10.8.0.1 dev eth0 scope link  src 10.8.0.4 

irc-client-0:/# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.8.0.1        0.0.0.0         UG    0      0        0 eth0
10.8.0.0        10.8.0.1        255.255.255.128 UG    0      0        0 eth0
10.8.0.1        *               255.255.255.255 UH    0      0        0 eth0
```

The middle route being`10.y.z.0/25 via 10.x.y.1` is what sends traffic to the host network for processing. I can't seem to replicate that using the bridge plugin here.

I was about to get closer by adding more routes:

```json
{...
        "routes": [
          { "dst": "0.0.0.0/0" },
          {"dst":"10.10.0.0/25","gw":"10.10.0.1"},
          {"dst":"10.10.0.1/32"}
        ],
...}
```

```
baff05a2cff5:/# ip route
default via 10.10.0.1 dev eth0 
10.10.0.0/25 dev eth0 scope link  src 10.10.0.65 
10.10.0.1 via 10.10.0.1 dev eth0 

baff05a2cff5:/# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.10.0.1       0.0.0.0         UG    0      0        0 eth0
10.10.0.0       *               255.255.255.128 U     0      0        0 eth0
10.10.0.1       10.10.0.1       255.255.255.255 UGH   0      0        0 eth0
```

This is still wrong though, container-->container traffic bypasses the gateway.

I was able to manually reconfigure a `bridge` container's routing to match what Kubernetes pods get:

```
fdf6eff03a76:/# ip route add 10.10.0.1 dev eth0 scope link src 10.10.0.62
fdf6eff03a76:/# ip route del 10.10.0.0/25 dev eth0 scope link  src 10.10.0.62
fdf6eff03a76:/# ip route add 10.10.0.0/25 via 10.10.0.1 dev eth0 src 10.10.0.62
```

This worked, but it's shitty and manual.

Any hope for being able to put the gateway on the host-local subnet?

Sorry for the somewhat vague issue, I'll be able to write up how I'm testing (with nftables and ping) if there's not enough details here.

**Comment by danopia** [comment]
I might have an explanation for the behavior I'm seeing:

```
37ff3f8db8ba:/# ip route
default via 10.10.0.1 dev eth0 
10.10.0.0/25 dev eth0 scope link  src 10.10.0.73 

37ff3f8db8ba:/# ip route add 10.10.0.0/25 via 10.10.0.1 dev eth0
ip: RTNETLINK answers: File exists
```

It looks like the route creation routine silently ignores routes that "already exist", so if the /25 route is created by something else beforehand (possibly by the linux bridge logic), IPAM would just fail and move on. Code here: https://github.com/containernetworking/plugins/blob/master/pkg/ipam/ipam_linux.go#L112-L117

**Comment by bboreham** [comment]
What CNI plugin is in use for your "how a normal Kubernetes pod is configured" case?

**Comment by matthewdupre** [comment]
Not being able to perform an L3 DNAT makes sense - in your first example traffic to that 10.10.0.0/25 subnet never needs to be processed by the IP layer of the host because it's just an ethernet frame direct to the MAC of the other pod.

To understand why you're getting different results we need more information about what plugins and how you're invoking them.

**Comment by danopia** [comment]
>What CNI plugin is in use for your "how a normal Kubernetes pod is configured" case?

Hah, good question because normally I'd just assume it's flannel or something else opaque. But I just checked this specific node and turns out it's just ptp:

```json
$ cat /etc/cni/net.d/10-containerd-net.conflist 
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "ptp",
      "mtu": 1460,
      "ipam": {
        "type": "host-local",
        "subnet": "10.8.0.0/25",
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ]
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      },
      "noSnat": true
    }
  ]
}
```

... so I just switched my podman test machine from bridge to that simple ptp config, which seems to be working great. I guess that's easy enough!

I'm looking at another kubernetes node of mine that definitely does use flannel, presumably with bridge underneath, and I'm not sure how it works tbh. The pod routes there are not agreeing with my initial thoughts on how kubernetes networking works:

```
default via 10.244.0.1 dev eth0 
10.244.0.0/24 dev eth0  proto kernel  scope link  src 10.244.0.65 
10.244.0.0/16 via 10.244.0.1 dev eth0 
```

>in your first example traffic to that 10.10.0.0/25 subnet never needs to be processed by the IP layer of the host because it's just an ethernet frame direct to the MAC of the other pod.

I think what was confusing me here is that replacing the /25 route in a running container to have a `via <gw>` clause was seemingly enough to have the host conntracking start processing the traffic again. I suppose that clause results in the host MAC address being used in the packets instead of the other pod's known MAC? I thought I understood linux networking 😅 

I guess that now that I see GKE leveraging `ptp` it seems easier to replicate with podman, so I'm ok closing this ticket if `bridge` is working as intended. If instead it seems like there is some undesirable inflexibility here, I'll put together a repro

**Comment by danopia** [comment]
The ptp plugin has been working great for my usecase, so I'll proactively close this.

I still think that the bridge plugin is flawed by silently failing to install gateway routes on its own subnet, but it doesn't seem to be a dealbreaker for most usecases. Indeed, I was able to work around the failure to install the above /25 route by installing two /26 routes (an adaption of the classic `0.0.0.0/1, 128.0.0.0/1` trick to take over the default route before there were APIs to do so). In which case bridge was tricked into passing inter-container traffic to the host for rewriting. So if the status quo is acceptable then I won't make too much noise about it.

Thanks for the replies.

**Comment by bboreham** [comment]
> how kubernetes networking works

It doesn't work in any specific way; that's the whole point of Kubernetes using CNI.
[This](https://kubernetes.io/docs/concepts/cluster-administration/networking/#the-kubernetes-network-model) is a concise statement of the requirements; it doesn't say anything about routes.

> I still think that the bridge plugin is flawed by silently failing

I think I agree, to the extent what it should do is ignore an _exact_ duplicate route; silently ignoring one that has the same destination but different details at least makes troubleshooting harder. 

Also I am reminded of this: https://github.com/containernetworking/cni/issues/598, which is a different thing but in the same area.
