### ISSUE TITLE
DHCP: correctly handle route fields

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#51]
From the RFC:
> If the DHCP server returns both a Classless Static Routes option and
   a Router option, the DHCP client MUST ignore the Router option.

>   Similarly, if the DHCP server returns both a Classless Static Routes
   option and a Static Routes option, the DHCP client MUST ignore the
   Static Routes option.

We do neither: we ignore the Router option and merge the Classless and Static sections.

**Comment by mzahorik** [comment]
I ran into this bug.  I've submitted https://github.com/containernetworking/plugins/pull/104 to correct.  I've spun up some nginx containers under Kubernetes with "classic" static routes (DHCP option 33) and all looks good including the containers getting a default route with the router as gateway.

This is the first time I've touched Go, and my Infobloxes don't allow me to specify classless static routes, so please check that everything looks right for adding the routes returned by parseCIDRRoutes()
