### ISSUE TITLE
iptables rule CNI-HOSTPORT-DNAT never come back after restart firewalld.service

### ISSUE THREAD

**Issue by mzyfree** [containernetworking/plugins#512]
**What happened**:
I have run kubernetes cluster while enable and running the firewalld.service on three node.
```
[root@node85 ~]# kubectl get no -owide
NAME     STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION               CONTAINER-RUNTIME
node85   Ready    master   8d    v1.15.6   10.99.212.85   <none>        H3Linux Release 1.1.1   3.10.0-957.21.3.el7.x86_64   docker://18.9.6
node86   Ready    master   8d    v1.15.6   10.99.212.86   <none>        H3Linux Release 1.1.1   3.10.0-957.21.3.el7.x86_64   docker://18.9.6
node87   Ready    master   8d    v1.15.6   10.99.212.87   <none>        H3Linux Release 1.1.1   3.10.0-957.21.3.el7.x86_64   docker://18.9.6
```
After I restart firewalld.service, it will clean up all iptables rule,including the kube-proxy iptables rules and CNI iptables rules.
```
[root@node85 ~]# iptables -nvL PREROUTING -t nat
Chain PREROUTING (policy ACCEPT 3 packets, 180 bytes)
 pkts bytes target     prot opt in     out     source               destination
 2151  182K PREROUTING_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 2151  182K PREROUTING_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 2151  182K PREROUTING_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0
```
After I wait for 30 seconds(iptables-sync-period), all iptables rules that belong to kube-proxy and CNI plugin calico are back on the node.Because both of them have watching and resetting iptables rules function.
```
[root@node85 ~]# iptables -nvL PREROUTING -t nat
Chain PREROUTING (policy ACCEPT 3 packets, 180 bytes)
 pkts bytes target     prot opt in     out     source               destination
 3427  258K cali-PREROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:6gwbT8clXdHdC1b1 */
 3429  258K KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
 2151  182K PREROUTING_direct  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 2151  182K PREROUTING_ZONES_SOURCE  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 2151  182K PREROUTING_ZONES  all  --  *      *       0.0.0.0/0            0.0.0.0/0
```
But the iptables rules that belong to CNI plugin portmapping never come back util I delete the pod which use hostport on the node.

**What you expected to happen**:
iptables rule CNI-HOSTPORT-DNAT  comes back after restart firewalld.service

**How to reproduce it (as minimally and precisely as possible)**:
1.deploy k8s
2.enable and start firewalld.service

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
[root@node85 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
You have new mail in /var/spool/mail/root
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
Centos 7.0
- Kernel (e.g. `uname -a`):
```
[root@node85 ~]# uname -a
Linux node85 3.10.0-957.21.3.el7.x86_64 #1 SMP Wed Jul 17 06:57:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
calico/portmapping...
- Others:

**Comment by wheatevo** [comment]
I am seeing a similar issue with Flannel on Oracle Linux 7 when firewalld is reloaded.

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Oracle Linux Server 7.9

Linux node01 3.10.0-1160.11.1.el7.x86_64 #1 SMP Tue Dec 15 11:58:45 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mars1024** [comment]
Now CNI plugins works as binaries called by kubelet, but kube-proxy or calico works as daemons which can do some cron jobs, such as detecting and repairing the lost iptables rules periodically.
So it's hard to require CNI plugins to bring iptables rules back until we introduce a new **CNI daemon**, but I think this is still under discussions.

**Comment by mohag** [comment]
It seems like the stable bot decided to close it....

**Comment by nnaghawai** [comment]
Stuck with this issue, was this ever resolved? any workarounds?

**Comment by wheatevo** [comment]
@nnaghawai 

The workaround we ended up using was to monitor ingress service health and to restart any running pods that did not have a working DNAT rule. The DNAT rule was recreated when the pod restarted.

**Comment by ccbcqbz** [comment]
The issue is still not fixed.

**Comment by mohag** [comment]
I need to check, but on modern OS versions where firewalld defailts to nftables, that might solve this without the problem actually being fixed...

**Comment by ccbcqbz** [comment]
RHEL 8 default firewall backend is nftables and this issue still happens.

**Comment by raelix** [comment]
I have the same issue when I upgrade Kubernetes using RKE. The ```CNI-HOSTPORT-DNAT``` chain has still old entry causing nginx-ingress-controller to become unreachable.
What I found:
```shell
Chain CNI-HOSTPORT-DNAT (2 references)
num  target     prot opt source               destination         
1    CNI-DN-2340674fa9a846ba6cee5  tcp  --  anywhere             anywhere             /* dnat name: "cbr0" id: "770c07dfd094fa98f07ed00c04920cc32b8f3be77d02d803b54b84cc1af77bb0" */ multiport dports http,https
2    CNI-DN-98502136a6caa3b998bdb  tcp  --  anywhere             anywhere             /* dnat name: "cbr0" id: "b57a45acaad108d4e72d396cef6f9f2bf4a354b6aac7c93c9ac5812e35495d40" */ multiport dports http,https
```
But only the second entry should be present.
