### ISSUE TITLE
[feature request]Is there any plan for supporting sr-iov backend?

### ISSUE THREAD

**Issue by xq2248** [containernetworking/plugins#517]
[feature request]Is there any plan for supporting sr-iov backend?

**Comment by jellonek** [comment]
It is covered by bunch of external projects like:
* https://github.com/hustcat/sriov-cni (afair first original one)
* https://github.com/intel/sriov-cni - intel fork of above (usually used in conjunction with https://github.com/intel/sriov-network-device-plugin on kubernetes)
* https://github.com/openshift/sriov-cni - which looks like newest of forks

**Comment by dcbw** [comment]
@jellonek https://github.com/openshift/sriov-cni is just the downstream OpenShift version of intel/sriov-cni; it's supposed stay aligned with the upstream one.

**Comment by xq2248** [comment]
@jellonek thanks
