### ISSUE TITLE
portMappings not supported in win-overlay

### ISSUE THREAD

**Issue by WeetA34** [containernetworking/plugins#530]
Hello,

i can't use win-bridge because of the target infrastructure which doesn't support it (antispoof policies, ...)
So i moved to win-overlay.
I would need portMappings also for win-overlay.
It has not been implemented in pull request 475 (https://github.com/containernetworking/plugins/pull/475)
Is-here any technical reason?

thank you
Regards
Stef

**Comment by billhong-just** [comment]
I am facing the same issue. 👀

**Comment by billhong-just** [comment]
I am facing the same issue. 👀
