### ISSUE TITLE
How would I implement Pod-To-Host over multiple VLANs?

### ISSUE THREAD

**Issue by CJCShadowsan** [containernetworking/plugins#550]
I have a use-case where I have a Pod that needs to be able to communicate Layer2 over VLANs - as it's effectively a DHCP server and IPMI controller...

...I've tried to use multus with the bridge CNI, and whilst I can get it to pick up it's IP address, I can't seem to get the pod to be able to contact hosts on the same VLAN.

Any tips, how-tos, or obvious gotchas would be appreciated - i'd prefer to use some standard plugins other than bridget - so bridge/macvlan options only. vlan can't be used, as it will only support 1 vlan device and I have... 4 networks I need to communicate on.

Thanks in advance!

**Comment by squeed** [comment]
Hmm - @SchSeba might know a few tricks.
