### ISSUE TITLE
[ENH] dhcp plug-in to support IPv6

### ISSUE THREAD

**Issue by ericzolf** [containernetworking/plugins#552]
Currently (AFAICJ, lack of documentation is obvious), the DHCP plug-in only handles IPv4, but I would also need IPv6. The plug-in could use SLAAC and/or DHCPv6, and offer via options dual-stack or single-stack.

**Comment by squeed** [comment]
Agreed, a dhcpv6 plugin (or dhcpv6 mode for the current plugin) would be nice.
