### ISSUE TITLE
No option to avoid IPAM with IPVLAN to create a L2 n/w

### ISSUE THREAD

**Issue by navjotsingh83** [containernetworking/plugins#572]
Hi,

We are in the process of deploying our legacy application to cloud-native space. The application is exposed publicly by providing external IPs to the PODs. We cannot use L7 Ingress concept for exposure as the protocol is non-http (DIAMETER).

Moreover, the legacy peers, that will connect to our application on the external IP(s), cannot talk to more than one IP, neither they can do FQDN based discovery. Therefore, in order to achieve High Availability, the IP needs to be moved from one POD to another in case the former POD is temporarily unavailable/evicted/restarted etc. We have figured out a solution to handle this IP movement independent of the CNI.

The issue that we are facing is that IPvLAN plugin, when used with multus, expects an IPAM. However, this is not the case with MACVLAN plugin. MACVLAN plugin can work without an IP to give a pure L2 network.  See this thread for more details : https://github.com/openshift/whereabouts-cni/issues/43#issuecomment-760462414

So as of now, since IP plumbing is mandatory, so we have to always plumb an extra static IP, and then plumb the actual floating-IP (which moves to another POD on failover), which will be used for the communication.

Our use-case is to support many-many IPs (around 44 in one deployment), so without this being fixed there is substantial IP wastage.

**Comment by mccv1r0** [comment]
> The issue that we are facing is that IPvLAN plugin, when used with multus, expects an IPAM. However, this is not the case with MACVLAN plugin. MACVLAN plugin can work without an IP to give a pure L2 network.

`macvlan` will use a unique ethernet address per interface. The port/NIC has one ethernet address for the "master" (e.g. host interface) and one for each container.  Where the ethernet frame receives is to be sent is unambiguous.

`ipvlan` shares the same ethernet address across all `ipvlan` interfaces.   Where the packet goes is based on the IP address.  CNI just configures Linux to use `ipvlan` inside the container.  Absent IPAM providing a unique IP address, how does the Linux kernel stack know where to send the packet in when you're looking to do?

**Comment by navjotsingh83** [comment]
_Absent IPAM providing a unique IP address, how does the Linux kernel stack know where to send the packet in when you're looking to do?_
The application will take care of the responsibility of plumbing the IP. That's the use-case since the application logic will know "Who owns the Quorum?" and thereby who will get the IP? So, the ask is that the IP delegation is left to the application. 

https://github.com/nokia/danm/ - Check out this CNI (it's a meta-cni + ipam + much much more) which is able to provide a "NO IP" option in its IPAM. We have used this with ipvlan plugin and got a successful interface in the POD with NO IP (see below). But the issue is that most customers prefer to use multus (and not DANM) so we were looking for support here.

_[root@danm-lab-control-01 ~]# kubectl exec -it <POD-name-hidden> -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if292: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8950 qdisc noqueue state UP group default
    link/ether 36:9d:a5:00:08:1a brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.32.246/32 scope global eth0
       valid_lft forever preferred_lft forever
**291: eth1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN group default
    link/ether fa:16:3e:78:65:70 brd ff:ff:ff:ff:ff:ff**_

**Comment by navjotsingh83** [comment]
@mccv1r0 - Do you have any updates on my comment? Are we on the same page?

**Comment by yanovich** [comment]
I've had the same issue on microk8s on ubuntu 20.04. Building from source and installing latest cni plugins helped.
