### ISSUE TITLE
host-device: Support IPAM for DPDK device

### ISSUE THREAD

**Issue by lynic** [containernetworking/plugins#578]
Hi team, host-device plugin support DPDK device since https://github.com/containernetworking/plugins/pull/490 merged, would be good to also support IPAM for DPDK device just like what SRIOV cni do. https://github.com/k8snetworkplumbingwg/sriov-cni/pull/142

**Comment by martinkennelly** [comment]
I like this idea. We use SRIOV CNI on baremetal to provide DPDK apps with an IP address via downward API however we depend on host-device plugin for now in a VM environment. If we got a general community acceptance on needing this feature, we could work on it.

**Comment by pperiyasamy** [comment]
@squeed  in dpdk case, yes, cni doesn't configure ip address on the interface, but it can still assign ip address from ipam module and pass back in result (this is what we intend to fix it here), this would help meta cni's like multus to build network status annotation for device with ip address. this is later mounted into pod container via downward APIs and dpdk application use this ip address in the user space.  
can we work on a PR to address this ?

**Comment by wjun** [comment]
@squeed We really would like this is get supported in host-device.
