### ISSUE TITLE
host-local hang because of mismatched startRange and startIP

### ISSUE THREAD

**Issue by gongguan** [containernetworking/plugins#594]
Many pods hang in creating and deleting process in our kubernetes cluster. I have dug into it and found a host-local process running for a long time without finished. After reading host-local plugin code, found an endless loop logic in multi-ipranges scenario.

### Bug report
In multi ip range scenario, when lastReservedIP is last ip of range i,
RangeIter will be init as `startRange = i, cur = lastReservedIP, starIP = nil`
when `RangeIter.Next()` called, `i.cur` will be changed as first ip of range i+1,
https://github.com/containernetworking/plugins/blob/a8d1f5cd1b132f10e5d86746ab82de1cd3c2b616/plugins/ipam/host-local/backend/allocator/allocator.go#L206-L211

then `startIP` will be changed too https://github.com/containernetworking/plugins/blob/a8d1f5cd1b132f10e5d86746ab82de1cd3c2b616/plugins/ipam/host-local/backend/allocator/allocator.go#L216-L217

but `iter.startRange` still equals i.
When no ip available, allocator Get() function can't jump out this [loop](https://github.com/containernetworking/plugins/blob/a8d1f5cd1b132f10e5d86746ab82de1cd3c2b616/plugins/ipam/host-local/backend/allocator/allocator.go#L91) from here https://github.com/containernetworking/plugins/blob/a8d1f5cd1b132f10e5d86746ab82de1cd3c2b616/plugins/ipam/host-local/backend/allocator/allocator.go#L218-L220

#579 and #583 can be alternative fixes, and #583 chosen as a better way because it's cleaner.

**Comment by bboreham** [comment]
Fixed by #583
