### ISSUE TITLE
portmap meta plugin exposes port to the whole Internet without any restriction using firewalld

### ISSUE THREAD

**Issue by waulee** [containernetworking/plugins#618]
This is a move from here:
https://github.com/containernetworking/cni/issues/830

The root cause of thid problem is that portmap plugin knows nothing about zonse of the firewalld, which is now default for current Fedora, RedHat and Centos distros.
I'm not copying the whos post as it can be read there. But bboreham sugested to move here. So the original Issue request could be close there.

**Comment by erig0** [comment]
Even with the SNAT being done in iptables the firewalld zones should still be able to filter the SNAT'd traffic, i.e. it can be dropped. Care should be taken as the packet has been translated so you'll have to match addresses/ports of the packet _after_ the SNAT.

**CAVEAT** (this caveat only applies if the firewalld backend is `iptables`):
If the CNI plugin also has ACCEPT rules in the filter tables, then it may accept the packet _without_ the firewalld rules being considered.

Addendum: If the firewalld backend is `nftables`, then even if the CNI ACCEPTs the packet in the filter table then the firewalld rules will still be considered.

**Comment by waulee** [comment]
There are two workaround for this issue:
- NO 1: is mentioned in the original port using ipset, but ipset is maintained totaly separatedly from firewalld zones. (at least in my case the my firewalld only use iptables, nut not yet ipsets, with it I had issues at the beginging)
-No 2: If the container IP can be kept FIX (ie. podmad --ip <FIXIP>) there is a second option. Simply run the pod without port expose (portmap plugin is do nothing): podman run --ip <FIXIP> <image> <cmd>. And let firewalld set port-forwards to the FIXIP in the desired zone. (eg.: firewall-cmd --zone=work --add-forward-port=port=8080:proto=tcp:toport=80:toaddr=10.88.0.10)

**Comment by waulee** [comment]
@erig0 That's correct. And this is my original problem. I'm used to the concept of the zones in firewalld. I was not aware ot this top level DNAT rule until i was forced to investigate is closely.
I'm also aware of the firewalld plugin too. But that only sets the sourcing traffic of the pod to the specified zone. Not the portmapped destination traffic. These two plugins are totally unrelated now, even the sequeqce of their occurance is up to the users choice.

This is partly awareness message of the danger it can be. Partly a feature request to solve this chicken-egg issue. Maybe a merger of the two plugin in case of firewalld is in use.

**Comment by unknowndevQwQ** [comment]
@waulee I'll mention the bad news here: this issue is closed due to obsolescence
