### ISSUE TITLE
Need help to install static ipam/cni plugin from repo

### ISSUE THREAD

**Issue by arifur2021** [containernetworking/plugins#637]
I have installed multus and now trying to install static ipam/cni plugin. There is no binary file for static in /opt/cni/bin directory and dont know hot to install using repo. ( following link)
https://github.com/containernetworking/plugins/tree/master/plugins/ipam/static
Would appreciate any help.

Thanks in advance.

**Comment by esampin** [comment]
Let me know @arifur2021 if you have a solution now to install the static ipam/cni plugin,

**Comment by arifur2021** [comment]
Hi @esampin , I have resolved the CNI plugin installation issue. 

You can install CNI plugin using one of the following options:
**Option-1: On Master node** 
- Install CNI plugins and copy all binaries to all worker nodes. 
**Option-2: On each worker node**
- Install CNI plugins and copy all binary files to /opt/cni/bin directory

**Pre-requisites:**

- Install snap which will require to install go
`$ sudo apt install -y snap
$ snap version`

- Install go using snap
`$ sudo snap install go --classic
$ which go`
If you have issue, logout and login again.

**Install CNI Plugins**

- Login to each worker node and execute following steps
- Download the CNI plugin from GIT repo using clone
` # git clone https://github.com/containernetworking/plugins.git`
`# cd plugins`
`# ls -l`

- Build the CNI plugin binaries using build_linux.sh script. Bi8naries will be in the /plugins/bin directory
`# cd plugins/`
`# ./build_linux.sh`

- Verify all binaries are built
`# cd bin/`
`# ls -l`
- Copy required/all binary files to /opt/cni/bin/ directory. Following example showing only static plugin
# cp static /opt/cni/bin/

- Verify required binaries are transferred to /opt/cni/bin/ directory
# cd /opt/cni/bin/
# ls -l

Sample Output:
`root@user-host1:/opt/cni/bin# ls -l
total 281524
-rwxr-xr-x 1 root root  4159518 Jun 15 21:12 bandwidth
-r-xr-xr-x 1 root root  4028260 Jan  1  2000 bridge
-rwxr-xr-x 1 root root 41472000 Jun 15 21:12 calico
-rwxr-xr-x 1 root root 41472000 Jun 15 21:12 calico-ipam
-rwxr-xr-x 1 root root 13979648 Jun 15 21:12 cilium-cni
-r-xr-xr-x 1 root root 10232415 Jan  1  2000 dhcp
-rwxr-xr-x 1 root root  3069556 Jun 15 21:12 flannel
-rwxr-xr-x 1 root root  3614480 Jun 15 21:12 host-local
-rwxr-xr-x 1 root root 41472000 Jun 15 21:12 install
-r-xr-xr-x 1 root root  3572685 Jan  1  2000 ipvlan
-rwxr-xr-x 1 root root  3209463 Jun 15 21:12 loopback
-r-xr-xr-x 1 root root  3613497 Jan  1  2000 macvlan
-rwxr-xr-x 1 root root 41874840 Jun 14 19:04 multus
-rwxr-xr-x 1 root root  3939867 Jun 15 21:12 portmap
-r-xr-xr-x 1 root root  3993428 Jan  1  2000 ptp
-r-xr-xr-x 1 root root  2641877 Jan  1  2000 sample
-rwxr-xr-x 1 root root  2978378 Jun 22 19:26 **static**		<<<<<<<<<<<
-rwxr-xr-x 1 root root  3356587 Jun 15 21:12 tuning
-r-xr-xr-x 1 root root  3568537 Jan  1  2000 vlan
-rwxr-xr-x 1 root root 38016417 Jun 17 15:41 whereabouts
root@user-host1:/opt/cni/bin#
`

Hope this will help.

Thanks,
Arifur

**Comment by esampin** [comment]
Thx @arifur2021. It works! Can you share the source/reference for this procedure?

**Comment by arifur2021** [comment]
Hi @esampin 

I did my research, compiled put together all info and made all those steps.

Thanks,
Arifur

**Comment by esampin** [comment]
Well done. This is really good!
