### ISSUE TITLE
Document how to use VLAN device/VLAN tagging.

### ISSUE THREAD

**Issue by gaby** [containernetworking/plugins#644]
Currently the documentatiom doesn't explain how to use a VLAN device. We tried using ipvlan, macvlan, bridge and none are working with vlan tagged traffic. Using the native docker ipvlan works though.

**Comment by MikeZappa87** [comment]
I actually have a PR opened for that in the cni.dev repo (https://github.com/containernetworking/cni.dev/pull/94)

For the vlan plugin I am pretty certain its equal to this command:
ip netns add cni-1
ip link add link wlp0s20f3 name wlp0s20f3.10 type vlan id 10
ip link set wlp0s20f3.10 netns cni-1
ip netns exec cni-1 ip link set wlp0s20f3.10 name eth0
.....

Maybe that helps a little?

**Comment by gaby** [comment]
I manage to get vlan devices to work by reading the code a few months ago, wished the documentation was provided.
