### ISSUE TITLE
macvlan plugin doesn't configure default route inside pod

### ISSUE THREAD

**Issue by syelburgi** [containernetworking/plugins#646]
Hi,

when pod is created with macvlan cni plugin. inside the pod's network namespace, I don't see default route is getting configured. as a result pod cannot communicate to public network(not local).

**Comment by MikeZappa87** [comment]
@syelburgi I left a comment on your PR #659 Does the "routes" key on the ipam not work here? See my network configuration in the PR comment! Have a good one!
