### ISSUE TITLE
multiple subnet in macvlan

### ISSUE THREAD

**Issue by leeminseob** [containernetworking/plugins#648]
Is it possible to two subnet in one macvlan file and assign only one IP to pod?
Can I create multiple subnets in one macvlan file and set them to be assigned on the second subnet if the first subnet is not available?

For example, Macvlan settings are shown below

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "em2",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "datadir": "/k8s/test",
        "ranges": [
          [
            {
              "subnet": "1.1.1.0/24",
              "rangeStart": "1.1.1.2",
              "rangeEnd": "1.1.1.3",
              "gateway": "1.1.1.1"
            }
          ]
        ],
        "ranges": [
          [
            {
              "subnet": "2.2.2.0/24",
              "rangeStart": "2.2.2.2",
              "rangeEnd": "2.2.2.3",
              "gateway": "2.2.2.1"
            }
          ]
        ]
      }
    }'
```

The expectations I want are as follows.

1. Two pods are created and these pods are assigned 1.1.1.2 and 1.1.1.3.
2. The pod that is then created is assigned from 2.2.2.0 because there are no IPs that can be assigned to the 1.1.1.0 subnet.

How can you solve this problem in the same situation as me?

**Comment by mars1024** [comment]
Of course, all you have to do is merging the two `ranges` into one, like
```
        "ranges": [
          [
            {
              "subnet": "1.1.1.0/24",
              "rangeStart": "1.1.1.2",
              "rangeEnd": "1.1.1.3",
              "gateway": "1.1.1.1"
            },
            {
              "subnet": "2.2.2.0/24",
              "rangeStart": "2.2.2.2",
              "rangeEnd": "2.2.2.3",
              "gateway": "2.2.2.1"
            }
          ]
        ],

```

**Comment by leeminseob** [comment]
@mars1024 
As you said, I modified the contents of the file.

However, two IPs are still assigned to one pad. It's not what I expected.

```
Add net1 [1.1.1.2/24 2.2.2.4/24] from default/macvlan-conf
```

**Comment by leeminseob** [comment]
@mars1024 
Thank you for your answer first.

It's working well.

**Comment by leeminseob** [comment]
@mars1024 
Thank you for your answer first.

It's working well.
