### ISSUE TITLE
set up golang-ci linter, fix codebase. 

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#663]
We really need a linter. Setting one up in github CI is [easy](https://github.com/golangci/golangci-lint-action).

The only problem: we need to fix all our lint failures :(

If anyone has spare time, or would like to get started with the project, run golangci-lint and file a PR fixing some issues found.

**Comment by MikeZappa87** [comment]
[lint.txt](https://github.com/containernetworking/plugins/files/7819332/lint.txt)

If anyone is curious this is the current output of golangci-lint run

**Comment by knabben** [comment]
I will take this one

**Comment by pigletfly** [comment]
@knabben are you still working on this? I'd like to give some help on this
