### ISSUE TITLE
bridge plugin:call ipam.ExecDel after clean device in netns

### ISSUE THREAD

**Issue by gojoy** [containernetworking/plugins#666]
https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/bridge.go#L635
now bridge plugin call ipam.ExecDel firstly and then clean device in netns when DEL, if  execute ipam.ExecDel successful but clean device failed, in this situation the ip has been released in ipam server, while the ip was still used in this netns, may cause ip conflict if ipam allocate the ip to another new pod.

should call ipam.ExecDel after clean device in netns ?
thanks

**Comment by mars1024** [comment]
I think your concern is indeed right, but two conditions below make sure ip conflict happened rarely,
1.  `host-local` use serial strategy for IP allocation, this means a released IP will not be reused unless IP range is running out
2. removing device is hard to fail, nearly impossible

**Comment by gojoy** [comment]
> I think your concern is indeed right, but two conditions below make sure ip conflict happened rarely,
> 
> 1. `host-local` use serial strategy for IP allocation, this means a released IP will not be reused unless IP range is running out
> 2. removing device is hard to fail, nearly impossible

yes，ip conflict happened rarely,  but it  happened  and cause some problem in my situation，the  basic reason why cni clean device failed is still under investigation. while we can avoid this by optimize the clean process in cni plugin, I have finished it and it works fine in my test environment .
Can I make a PR for this？
Thanks
