### ISSUE TITLE
Plugin release 1.0.1 doesn't support CNI version 1.0.1

### ISSUE THREAD

**Issue by danslimmon** [containernetworking/plugins#668]
I downloaded the CNI plugins package at `https://github.com/containernetworking/plugins/releases/download/v1.0.1/cni-plugins-linux-amd64-v1.0.1.tgz` and extracted the tarball to `/opt/cni/bin`. When I use the `VERSION` command against the plugins therein, they do not announce support for CNI version 1.0.1:

```
root@my-host:/opt/cni/bin# for f in *; do CNI_COMMAND=VERSION ./$f <<<'{"cniVersion":"1.0.1"}'; done
{"cniVersion":"1.0.0","supportedVersions":["0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","1.0.0"]}
{"cniVersion":"1.0.0","supportedVersions":["0.3.1","0.4.0","1.0.0"]}
```

I would expect the plugins packaged as v1.0.1 to support v1.0.1. Perhaps it is my expectation that is wrong. Please advise.

**Comment by dcbw** [comment]
@danslimmon I think the confusion here is the difference between the CNI *specification* version, and the CNI software version.

Plugins report the CNI spec version they support. But the plugins software itself, and tarballs, etc versioning is not the same as the CNI spec version. So the plugins are at v1.0.1 because we found a bug in 1.0.0 in the code, but the CNI spec itself is still 1.0.0.

Does that clarify things?

**Comment by danslimmon** [comment]
@dcbw Very much so, thank you. Is it the case, then, that the CNI specification version should always end in `.0`? Or should I not necessarily depend on that?

**Comment by danslimmon** [comment]
@dcbw Very much so. Thank you.
