### ISSUE TITLE
IPVLAN does not support GARP

### ISSUE THREAD

**Issue by ryanlyy** [containernetworking/plugins#673]
when using multus/IPVLAN, if pod schedule from one node to another node, GARP is not sent to update its neighbor arp cache. Then incoming traffic will not go to the new node instead going to old node until its neighbor arp cache timeout. 

The expected behavior is that when adding ip to ipvlan device, ipvlan can send gARP to update its neighbor arp cache, then incoming traffic can go to the correct node/pod.

**Comment by ryanlyy** [comment]
any suggestion on above issue?

**Comment by TothFerenc** [comment]
I can see that MACVLAN sends GARP: https://github.com/containernetworking/plugins/blob/e27c48b391539f5536918b9c379c59ef2793cb0d/plugins/main/macvlan/macvlan.go#L308
Is it missing from IPVLAN intentionally? Can we add it?

**Comment by mars1024** [comment]
@ryanlyy @TothFerenc Good catch! Could you help to pull a request to fix this?

**Comment by TothFerenc** [comment]
@mars1024 Can you please check this PR above? Thanks!
