### ISSUE TITLE
Proposal: improved routing

### ISSUE THREAD

**Issue by oskarirauta** [containernetworking/plugins#677]
My problem is that my host system (OpenWrt) cannot reach container(s)/pod(s) properly and eventually I was able to fix this by changing the route.. route coming from cni is:

`
10.129.0.0/24 dev cni-podman0 proto kernel scope link src 10.129.0.1
`

I can fix this with following:

```
ip route del 10.129.0.0/24
ip route add 10.129.0.0/24 dev cni-podman0 proto kernel scope link via 10.129.0.1 src $LAN_IP
```

10.129.0.0/24 is my cni network subnet, and gw is 10.129.0.1

so I am wondering if we could have optional fields to route with via and src - netlink go module used already does support it.

**Comment by MikeZappa87** [comment]
Do you have multiple ip addresses assigned to the interface?

**Comment by MikeZappa87** [comment]
This looks like the source address selection algorithm in Linux is not your friend which is usually the case when src is used. I am guessing you have multiple ip addresses assigned?

**Comment by oskarirauta** [comment]
Problem solved. It was a firewalling issue instead.
