### ISSUE TITLE
portmap doesn't work with hairpin

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#68]
When a container tries to talk to itself (over the portmapped "host" ip + port), it doesn't work. It should.

**Comment by squeed** [comment]
The most obvious solution is to add an additional MASQ rule that rewrites the source IP to the host itself. This works, but I'm not sure how to set up the rule structure efficiently. @freehan maybe you have some suggestions?

**Comment by dcbw** [comment]
@squeed word on the street is you want to twiddle accept_local or route_localnet, not sure which.

**Comment by squeed** [comment]
There's no way to do this without a host-MASQ, because the souce port of the responding packet (i.e. a SYN/ACK) will be wrong.
