### ISSUE TITLE
Proposal : Worker nodes running out of IPs in IP range after node reboot

### ISSUE THREAD

**Issue by Nishant-Nayan** [containernetworking/plugins#697]
I have a kubernetes cluster with one worker node.
When I schedule a deployment of say 'n' pods and then reboot my worker node, then after the node comes up, I can see the old 'n' ips still present in '/var/lib/cni/networks/{dataDir}' directory, it also contains the newly assigned 'n' ips starting from the ip mentioned in 'last_reserved_ip' file. 
So totally I got 2n ips of which 'n' are unused. If I reboot my worker node further then eventually I will run out of Ip address throwing me then error "no IP addresses available in range set : <ip-range>" .

Proposed fix - One possible fix could be to track the reboots of worker nodes. When the node comes up then we can differentiate which ip files are created before the last reboot time and delete those as they are unused and keep the one's which are newly assigned (i.e after the last reboot).

Any suggestions/feedback on this would be appreciated.

**Comment by mel1nn** [comment]
+1 for this kind of feature

**Comment by dgloe-hpe** [comment]
I've noticed this same issue; here's the workaround we're using.

Create a file /usr/lib/tmpfiles.d/macvlan.conf with this content:
```
# Remove local macvlan reserved IP address information at boot time
r! /var/lib/cni/networks/*/*
```

That will cause systemd to remove the leftover reservations at boot time.
