### ISSUE TITLE
Why GetCurrentNS() must give us host's namespace in ns.Do()?

### ISSUE THREAD

**Issue by dunjut** [containernetworking/plugins#70]
https://github.com/containernetworking/plugins/blob/556e50909705ac6e46a2806a663f03bec09408e6/pkg/ns/ns.go#L127-L167

Hi team, I'm learning the **NetNS** code then get a small questions here.

L149 `hostNS, err := GetCurrentNS()`

  I think `GetCurrentNS()` just gives us current thread's namespace, how can we make sure it is host's namespace (considering `ns.Do` may be possibly invoked in container namespace)?

**Comment by squeed** [comment]
It's just bad terminology. The function starts in namespace A, switches to B, executes the function, then returns to A. We call them Host and Container but, as you point out, those aren't really correct.

The names aren't revealed to the library consumers so it doesn't matter much, except for confusing newcomers :-). It is a good question, though.

**Comment by dunjut** [comment]
@squeed Thanks for clarification. I have another question, why do we `GetCurrentNS()` twice? (L149 and L133) And what is `containedCall`, is that a typo of `containerCall`?

**Comment by squeed** [comment]
I'm not exactly sure, but I do know that anytime you spawn a new goroutine, even if you've called `runtime.LockOSThread()`, you can't know which OS thread will run that goroutine. This is the ultimate problem with trying to manipulate os-thread-level properties in Golang. It just wasn't really made for it.

I'm going to close this issue - if you have more questions, come find us on our Slack or IRC channels.
