### ISSUE TITLE
loopback plugin need rootNS validation reinforcement

### ISSUE THREAD

**Issue by Poor12** [containernetworking/plugins#714]
In the case of repeated creation and deletion of containers, when the request is queued and delayed processing, there is a probability that the netns /proc/{pid}/ns/net in the cni request expires, at which time the original container has been destroyed, the original process has exited, and pid is occupied by other host processes, resulting in the namespace becoming the host namespace. When uninstalling the container LO NIC, the host's LO NIC is uninstalled by mistake.

**Comment by squeed** [comment]
This is definitely a problem! But, existing container runtimes (podman, docker) no longer pass pid-based namespaces anymore! Who is doing this!?

**Comment by squeed** [comment]
We talked about this at the maintainer's meeting, and we decided it would be better to fix this in `skel` for all plugins. Basically, one should fail to execute if the plugin's netns and CNI_NETNS point to the same place. There could be an environment variable, CNI_NETNS_OVERRIDE if this is somehow desired.

Make sense? Is this something you could take care of, @Poor12?

**Comment by Poor12** [comment]
I basically understand what you mean, but I want to confirm one thing, is CNI_NETNS_OVERRIDE similar to a switch to determine whether netns verification is required? @squeed

**Comment by squeed** [comment]
@Poor12 exactly right - if that environment variable is set, then we skip the same-netns check. Otherwise we should just add this to `skel`, and thus include in every plugin.
