### ISSUE TITLE
Should we maintain windows CNI for containerd

### ISSUE THREAD

**Issue by YanzhaoLi** [containernetworking/plugins#722]
I think win-bridge and win-overlay are specific for dockerd as runtime. For containerd on windows, I only know sdnbridge works.

**Comment by dcbw** [comment]
@YanzhaoLi CNI maintainers are working with Microsoft to determine whether the CNI reference plugins will continue to be maintained in CNI, or whether we will deprecate them and redirect people to the Microsoft forks. Stand by for more info soon...

**Comment by leandroscardua** [comment]
Hi @dcbw 

I hope you're doing well
Do you have any news on that topic?
