### ISSUE TITLE
plugins size add up and is too big

### ISSUE THREAD

**Issue by martinetd** [containernetworking/plugins#737]
Hello,

I'm using podman with cni-plugins on a minimal alpine host, whose only job is to run containers.. and almost 1/4 of the installed size comes from cni-plugins.

Each plugin isn't so big but it adds up; this was on alpine package 1.0.1-r1
```
2.6M	/usr/libexec/cni/bandwidth
2.9M	/usr/libexec/cni/bridge
6.5M	/usr/libexec/cni/dhcp
2.9M	/usr/libexec/cni/firewall
2.6M	/usr/libexec/cni/host-device
2.2M	/usr/libexec/cni/host-local
2.7M	/usr/libexec/cni/ipvlan
2.3M	/usr/libexec/cni/loopback
2.7M	/usr/libexec/cni/macvlan
2.5M	/usr/libexec/cni/portmap
2.9M	/usr/libexec/cni/ptp
2.4M	/usr/libexec/cni/sbr
2.0M	/usr/libexec/cni/static
2.4M	/usr/libexec/cni/tuning
2.7M	/usr/libexec/cni/vlan
2.5M	/usr/libexec/cni/vrf
45M	total
```
And this is the package upgraded to 1.1.1-r2 (rebuild on same system):
```
3.2M	/usr/libexec/cni/bandwidth
3.5M	/usr/libexec/cni/bridge
8.2M	/usr/libexec/cni/dhcp
3.6M	/usr/libexec/cni/firewall
3.2M	/usr/libexec/cni/host-device
2.7M	/usr/libexec/cni/host-local
3.3M	/usr/libexec/cni/ipvlan
2.9M	/usr/libexec/cni/loopback
3.4M	/usr/libexec/cni/macvlan
3.2M	/usr/libexec/cni/portmap
3.4M	/usr/libexec/cni/ptp
3.0M	/usr/libexec/cni/sbr
2.5M	/usr/libexec/cni/static
2.9M	/usr/libexec/cni/tuning
3.3M	/usr/libexec/cni/vlan
3.0M	/usr/libexec/cni/vrf
55M	total
```

When my whole system fits under 200MB, cni-plugins is now over 1/4 of it (and podman a good runner up); I'd like to see if this could be improved.

A naive idea that comes to mind is to work like busybox or coreutils configured with --enable-single-binary: bundle everything in a single binary, and have the program behaviour depend on argv[0].
I didn't try but I'd expect shared dependencies make up a good part of these 45MB and the final size would drop quite a bit.

I've never done any work on go buildsystem so I'm not really sure how to proceed, but if you're OK with the idea I'd be happy to give it a try (unless someone familiar with the project wants to do it)

Likewise, if this has already been tried somewhere else pointers would be appreciated!

Thanks

**Comment by dcbw** [comment]
I think this is more an artifact of how Go works... Go binaries are usually pretty big, unfortunately, because Go statically links everything.

**Comment by martinetd** [comment]
@dcbw please see #738 for a possible implementation of my idea of "making it like busybox" (not suggesting it gets merged as is, but it's a first step)

That being said, yes, moving away from go would likely yield even better results -- but I think code maintenance is also important and I'm not an active contributer so I don't think I have a say about this. Please keep using whatever language you feel most productive with.
I'm sure at some point someone will come and say "let's rewrite it in rust", but that won't be me :)
