### ISSUE TITLE
Feature request: support IPv6 in dhcp

### ISSUE THREAD

**Issue by florath** [containernetworking/plugins#744]
Currently dhcp ipam plugin only supports IPv4.
As Kubernetes supports dual stack since some time now, IPv6 support should be added.

**Comment by florath** [comment]
SLAAC / IPv6 link local addresses is working. But they are not routable.
Also host-local address assignment for IPv6 'global' (non link-local) addresses works fine.

What does not work for IPv6 is dhcp ipam.
What I see in the traces and the source code is, that only DHCP4 is implemented. Which means: when I start a pod using e.g. multus in a dual stack kubernetes only the IPv4 address will be assigned using DHCP.

I need that 'global' IPv6 addresses can be assigned to the multus netX network interfaces - in a very similar manner than for IPv4 (of course the DHCP protocol differs for IPv4 and IPv6).

**Comment by ajacques** [comment]
SLAAC can provide global IPv6 address if you have router adverts/prefix delegation setup on your network which is a very common deployment pattern. It is possible to enable this using the tuning CNI plugin:

```
{
  "type": "tuning",
  "sysctl": {
    "net.ipv6.conf.eth0.autoconf": "1",
    "net.ipv6.conf.eth0.accept_ra": "1",
    "net.ipv6.conf.eth0.disable_ipv6": "0"
  }
}
```

However, AFAIK these IP addresses won't pass through the CNI config and ultimately into Kubernetes on the pod status.

**Comment by mccv1r0** [comment]
> However, AFAIK these IP addresses won't pass through the CNI config and ultimately into Kubernetes on the pod status.

Agreed.  Currently the container will have them but the runtime will not know anything about them.  With podman I use this for (delegated prefix) end to end IPv6 connectivity.

With dhcpv6 (a proper one anyway) you'll get /128 and still need to look to RA for what prefixes are on-link, routers (which will most likely be LL address(es) anyway.  So same problem as the SLAAC case.
