### ISSUE TITLE
host-device: Move multiple devices into a container

### ISSUE THREAD

**Issue by nakabonne** [containernetworking/plugins#748]
Hello, thank you for all of your efforts.

I have a question about the `host-device` plugin. I would like to add multiple network devices like `can0` and `can1` into a container, but seems like that plugin allows only one device.

As far as I can tell from source code, it's not so difficult. We just have to add an interface to [100.Result](https://pkg.go.dev/github.com/containernetworking/cni@v1.1.0/pkg/types/100#Result).Interface. My question is if it's reasonable to let `host-device` support multiple devices.

Thank you.

**Comment by mccv1r0** [comment]
To add multiple devices you need multiple CNI ADD calls, e.g. one for `can0` and then another for `can1`.

**Comment by nakabonne** [comment]
Ah, that makes sense! Thank you for your quick reply!
