### ISSUE TITLE
DHCP daemon error: no DHCP packet received within 10s

### ISSUE THREAD

**Issue by dhamodaran-pandiyan** [containernetworking/plugins#751]
_**Carried from [containernetworking/cni](https://github.com/containernetworking/cni/issues/900) , as this is the right platform to post this,**_

Hi, I'm facing the below mentioned issue while using DHCP IPAM plugin + Macvlan + Multus for the additional interface creation inside my pod and assigning IP from DHCP server. 

I actually went through the related issues around this problem and tried all the solutions/different configurations mentioned there. But none of them were working so far. The documentation for CNI plugin w.r.t DHCP usage also not quite clear.

**Related Issues:**
1. https://github.com/k8snetworkplumbingwg/multus-cni/issues/291 
2. https://github.com/containernetworking/plugins/issues/587
3. https://github.com/containernetworking/plugins/issues/371
4. https://github.com/containernetworking/plugins/issues/440
5. https://github.com/containernetworking/cni/issues/398
6. https://github.com/containernetworking/cni/issues/225
7. https://github.com/containernetworking/plugins/issues/371

**Solutions Suggested:**
1. https://github.com/containernetworking/plugins/pull/577
2. https://www.cni.dev/plugins/current/ipam/dhcp/#operation

**DHCP Daemon Logs:**
```
[root@test-node cni_plugins]# ./dhcp daemon -broadcast=true
2022/06/09 12:00:03 ac7d57597540992a1af43455da24b3210561ce12b164820ee18f583a304a/test_net_attach1/net1: acquiring lease
2022/06/09 12:00:03 Link "net1" down. Attempting to set up
2022/06/09 12:00:03 network is down
2022/06/09 12:00:03 retrying in 2.881018 seconds
2022/06/09 12:00:16 no DHCP packet received within 10s
2022/06/09 12:00:16 retrying in 2.329120 seconds
2022/06/09 12:00:29 no DHCP packet received within 10s
2022/06/09 12:00:29 retrying in 1.875428 seconds

```

**NetworkAttachmentDefinition:**
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: "test1"
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/test_net_attach1
spec:
  config:
    '{
    "name": "test_net_attach1",
    "type": "macvlan",
    "master": "ens2f0",
    "ipam": {
        "type": "dhcp"
    }
    }'
```

**Test Pod YAML:**
```
apiVersion: v1
kind: Pod
metadata:
  name: dhcp-test1
  annotations:
    k8s.v1.cni.cncf.io/networks: test1
spec:
  nodeSelector:
    deploy: vm1
  containers:
    - name: c1
      image: centos:latest
      command: ["/bin/sh","-c"]
      args: ["sleep infinity"]

```

**DHCP SERVER Logs:**
```
Internet Systems Consortium DHCP Server 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Config file: /data/dhcpd.conf
Database file: /data/dhcpd.leases
PID file: /var/run/dhcpd.pid
Wrote 0 leases to leases file.
Listening on LPF/ens2f0/b4:96:91:a5:8c:82/192.168.231.0/24
Sending on   LPF/ens2f0/b4:96:91:a5:8c:82/192.168.231.0/24
Sending on   Socket/fallback/fallback-net
Server starting service.
DHCPDISCOVER from 4a:63:ad:6d:9a:44 via ens2f0
DHCPOFFER on 192.168.231.120 to 4a:63:ad:6d:9a:44 via ens2f0
DHCPDISCOVER from 4a:63:ad:6d:9a:44 via ens2f0
DHCPOFFER on 192.168.231.120 to 4a:63:ad:6d:9a:44 via ens2f0
```
**Observations:**
1. DHCP request and response are seen by tcpdump on the interface but the dhcp daemon says none was received.
2. Looks like the DHCP daemon is not picking up the offer.

**ENVIRONMENT:**
CNI: cni-plugins-linux-amd64-v1.1.1.tgz

Could someone please share the working configurations for the below mentioned items
1. Network attachment definition
2. Sample Pod YAML
3. How to run DHCP Daemon?

for the better documentation and for the new comers who is facing issues around this? Please let me know if you needed anything or if I'm missing anything?

**Comment by dhamodaran-pandiyan** [comment]
Team, Could you please comment on this?

@[rosenhouse](https://github.com/rosenhouse) @[steveeJ](https://github.com/steveeJ) @[dcbw](https://github.com/dcbw) @[eyakubovich](https://github.com/eyakubovich) @[SilverBut](https://github.com/SilverBut) @[mbrancato](https://github.com/mbrancato)

**Comment by ajacques** [comment]
I have this working (although I used the bridge CNI instead of macvlan due to conflicts with how K8s service routing works) and I've documented how to get this working on [my blog](https://www.technowizardry.net/2022/04/multus-with-calico-and-layer2-bridge/) However this required [forking](https://github.com/ajacques/cni-plugins) the CNI repository to fix several issues I've found that I haven't figured out which changes should be merged back in.

This error effectively means that the DHCP client attached to the container netns/interface didn't receive the response packet. Is your DHCP server running on the same host as your K8s worker or a different host? 

Are there any iptables rules filtering the responses? Check the FORWARD and INPUT chains to see if they're dropping packets. IIRC, one of the reasons I moved from macvlan to bridge is because macvlan packets wouldn't hit the host's iptables stack so they would get rejected on the way back because they were not related to an existing connection flow in the host stack.

**Comment by dhamodaran-pandiyan** [comment]
Thanks for your reply. Surely I'll take a look at your works. 

_Is your DHCP server running on the same host as your K8s worker or a different host?_
Yes, DHCP server is running in the k8s worker node only. 

_Are there any iptables rules filtering the responses?_
I don't see any packets being dropped/filtered out on the IP table. (TX and RX DRP columns)

```
[root@test-node k8s_dhcp_test]$ netstat -i
Kernel Interface table
Iface         	  MTU	    RX-OK    RX-ERR     RX-DRP RX-OVR	  TX-OK     TX-ERR     TX-DRP     TX-OVR     Flg
cali366d1b5f0f2   1440    	0  	0  	   0     0         0  	        0  	0  	   0     BMRU
cali7afcddg5a4f   1440	    15597  	0  	   0     0    	130033  	0  	0  	   0     BMRU
calib8sfffbaa5f   1440    	0  	0  	   0     0         	 0  	0  	0  	   0     BMRU
docker0      	  1500    	0  	0  	   0     0         	 0  	0  	0  	   0     BMU
eno1         	  1500  130151425  	0  	   0     0    71003986  	0  	0  	   0     BMRU
ens2f0       	  9600	    19213  	0  	   0     0     	 32346  	0  	0  	   0     BMRU
lo          	 65536  111155436  	0  	   0     0   111155436  	0  	0  	   0     LRU
tunl0        	  1440    	0  	0    	   0     0     0    	        0  	0     	   0      ORU
virbr0       	  1500    	0  	0  	   0     0     0   	        0  	0  	   0       BMU

```

**Comment by ajacques** [comment]
It'll be difficult to debug this issue with just this output you provided. Netstat shows physical layer issues which won't matter here. Are there any other rules in FORWARD that may be dropping packets? Does inserting a temporary ACCEPT help? `sudo iptables -I FORWARD 1 -j ACCEPT`

Does your host know where the container is? ` ip neigh | grep {container mac/ex: 4a:63:ad:6d:9a:44}`

Does `sudo tcpdump -i any -f 'udp port 68'` show the DHCPOFFER packet going back towards the container interface?
