### ISSUE TITLE
proposal: vxcan and cangw plugin

### ISSUE THREAD

**Issue by nakabonne** [containernetworking/plugins#753]
Hello Team, I would like to ask if we can make a new plugin for my use case, or if there is another way to do that.

I would like to forward real CAN Bus traffic between a USB-CAN adapter and a container without exposing the entire host network to the container. To do that, we need to create two [vxcan](https://cateee.net/lkddb/web-lkddb/CAN_VXCAN.html) interfaces. One will be put on a host and another will need to be inserted into a container.
To forward traffic from a real CAN adapter into the container, [can-gw](https://manpages.debian.org/testing/can-utils/cangw.1.en.html) is also needed.
What I want to do when creating a container is:

```
docker run --rm -it --name cantest ubuntu:20.04 &

DOCKERPID=$(docker inspect -f '{{ .State.Pid }}' cantest)
sudo ip link add vxcan0 type vxcan peer name vxcan1 netns $DOCKERPID
sudo modprobe can-gw
cangw -A -s can0 -d vxcan0 -e
cangw -A -s vxcan0 -d can0 –e
sudo ip link set vxcan0 up
sudo ip link set can0 type can bitrate 125000
sudo ip link set can0 up
sudo nsenter -t $DOCKERPID -n ip link set vxcan1 up
```

Do you think it is reasonable to make a new plugin for this case and put this repository? If something is unclear, please ask me.
Thanks!

**Comment by nakabonne** [comment]
I don't know who is familiar with this area but it would be great if I could get some inputs from @trusch who created `host-device` plugin to forward CAN Bus traffic.

**Comment by trusch** [comment]
That was the initial usecase for the host device plugin. My thought was that the bus can only be used by a single process anyway so setting up a special tunnel would be overkill. Therefore I had a systemd unit which configured the CAN bus in a pre-start statement and then moved the CAN bus device into the container using the host-device plugin. It worked like a charm!

Best of luck with your usecase :)
