### ISSUE TITLE
`loopback` plugin has no documentation

### ISSUE THREAD

**Issue by dilyanpalauzov** [containernetworking/plugins#759]
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#loopback-cni says Kubernetes needs the CNI loopback plugin.  The latter is not mentioned at https://www.cni.dev/plugins/current/ and is not documented.

**Comment by MikeZappa87** [comment]
@dilyanpalauzov I think we decided to deprecate that plugin and leave it to the runtime to set lo to up. Right now CRI-O does not use the loopback plugin and containerd does. I was actually going to implement the code to remove the loopback plugin from contianerd.

**Comment by dilyanpalauzov** [comment]
Why does Kubernetes say, that the CNI-lookup plugin is required by Kubernetes — https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#loopback-cni, while at the same time Kubernetes does not use CNI?

The above citation says:
> Kubernetes requires container runtimes to provide a loopback interface `lo`.  Implementing the loopback interface can be accomplished by re-using the [CNI loopback plugin](https://github.com/containernetworking/plugins/blob/master/plugins/main/loopback/loopback.go).

**Comment by MikeZappa87** [comment]
That article is out of date, especially in regards to CRI-O. The loopback is just setting loopback to up since the Linux kernel creates the loopback interface. Once the changes to containerd are made that documentation will need to be modified.

**Comment by dilyanpalauzov** [comment]
I filled https://github.com/kubernetes/website/issues/35456.
