### ISSUE TITLE
add an option to disable iptables

### ISSUE THREAD

**Issue by rtgiskard** [containernetworking/plugins#762]
I'm using nftables with customized rules, and do not want any part of the system to alter the rules itself, so that all the firewall rules can be managed in one place and easy to check.

currently cni plugin will always load iptable related module and set iptable rules, for my case, as nftables is in use, it would be a mess.

Add nftable backend might be a solution, but It would be good enough to have an option to disable iptables or any other firewall manipulation just like [docker](https://docs.docker.com/network/iptables/#prevent-docker-from-manipulating-iptables)

**Comment by rtgiskard** [comment]
related issue: [podman netavark](https://github.com/containers/netavark/issues/339)

**Comment by mccv1r0** [comment]
You have the option to not use `portmap` and `firewall` plugins.  And set `ipMasq=false` if the bridge plugin is the main plugin used.  Is there something else missing?

**Comment by rtgiskard** [comment]
> You have the option to not use `portmap` and `firewall` plugins. And set `ipMasq=false` if the bridge plugin is the main plugin used. Is there something else missing?

Great thanks! update cni network config, set `ipMasq=false` and remove the `portmap` and `firewall` part to disable the two plugins, then it works!
