### ISSUE TITLE
[feature request] `portmap` support `masquerade-all` option

### ISSUE THREAD

**Issue by BSWANG** [containernetworking/plugins#771]
When k8s cluster use `ipvlan` L3/L2, `macvlan` or other `underlay` network plugin.  The traffic come back from pod to host maybe not go through `conntrack` in host, and can not un-snat to `hostip` which client requested.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/3598874/197778103-8da44499-3cc1-4073-99a3-9d8a3c3f3eae.png">

Masquerad all traffic can make sure the pod reply come back to host and go through `conntrack` in host.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/3598874/197778515-a957cd2e-2dec-40d0-9cb6-04ae6a031d5e.png">

**Comment by mccv1r0** [comment]
I'm having trouble understanding what is going on.  

What addresses live where?

**Comment by dcbw** [comment]
@BSWANG can you clarify the diagram? What are 1.1.1.1 and 2.2.2.2?

Is the square a node in a cluster? And is 192.168.0.1 and 0.2 NICs on the node?

Is 10.0.0.1 the container?

**Comment by dcbw** [comment]
In your use-case, what is the source-ip and dest-ip of the incoming packet from client -> pod?

When the pod replies, what is the source-ip and dest-ip of hte outgoing packet?

**Comment by BSWANG** [comment]
@dcbw @MikeZappa87 
Thanks for reply. I have updated the description, for some `underlay` plugins scenarios.
