### ISSUE TITLE
Version numbers not consistent with releases

### ISSUE THREAD

**Issue by shwill** [containernetworking/plugins#774]
I do not seem to find a consistent way to see if CNI plugins require updating by querying the `-Version` flag on the pre-compiled binaries. Release v1.1.1 states changes to `ipam/dhcp` and `bridge`, running them all with the version flag outputs

```
CNI bandwidth plugin v0.8.6
CNI bridge plugin v0.8.6
CNI dhcp plugin v0.8.6
CNI firewall plugin v0.8.6
CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.0
CNI host-device plugin v0.8.6
CNI host-local plugin v0.8.6
CNI ipvlan plugin v0.8.6
CNI loopback plugin v0.8.6
CNI macvlan plugin v0.8.6
CNI portmap plugin v0.8.6
CNI ptp plugin v0.8.6
CNI sbr plugin v0.8.6
CNI static plugin v0.8.6
CNI tuning plugin v0.8.6
CNI vlan plugin v0.8.6
CNI vrf plugin v1.1.1
```

Both components state a v.0.8.6. 

I am trying to compile a playbook to install Kubernetes and I want it to be idempodent, but I cant seem to accomplish this for the CNI plugins. I would have either assumed that any plugin would report the release version number. Do I need to collect all version numbers and find the greatest value to be sure or do you have an alternative suggestion for me?

**Comment by afbjorklund** [comment]
These are supposed to be the same, there was a bug in the `kubernetes-cni` packaging that used 0.8.6 binaries for all.

kubernetes-cni_1.1.1-00_amd64.deb

$ ./kubernetes-cni_1.1.1-00/opt/cni/bin/bridge --version
CNI bridge plugin v0.8.6

The tarballs from https://github.com/containernetworking/plugins/releases should **not** suffer from this kubernetes/release issue.

cni-plugins-linux-amd64-v1.1.1.tgz

./cni-plugins-linux-amd64-v1.1.1/bridge --version
CNI bridge plugin v1.1.1

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/release/issues/821
