### ISSUE TITLE
flanneld

### ISSUE THREAD

**Issue by fmelon2** [containernetworking/plugins#776]
Will the new version no longer maintain flanneld plugins?

**Comment by afbjorklund** [comment]
The plugin now lives here https://github.com/flannel-io/cni-plugin

But normally it is installed by an init container in kube-flannel.yml

**Comment by afbjorklund** [comment]
* #633

**Comment by fmelon2** [comment]
> * [插件： 删除法兰绒 #633](https://github.com/containernetworking/plugins/pull/633)

Do you know the difference between the use of cni and cnipulgin? Or are these two used together? When switching the configuration file of containerd runtime flanneld, you should check those documents, how to confirm the version of the plugin and the cniVersion configuration in the configuration file? can you answer me

**Comment by afbjorklund** [comment]
Looking at the current version of [flannel](https://github.com/flannel-io/flannel), v0.19.2, it uses [flannel cni plugin](https://github.com/flannel-io/cni-plugin) v1.1.0 (i.e. together)

https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

In the _generated_ configuration, /etc/cni/net.d/10-flannel.conflist. you can check the cni version:

```json
{
  "name": "cbr0",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}

```

**Comment by fmelon2** [comment]
非常感谢你的解答
