### ISSUE TITLE
setsockopt returns ENOPROTOOPT for NETLINK_EXT_ACK

### ISSUE THREAD

**Issue by cadeniyi** [containernetworking/plugins#785]
Using the latest CNI plugins on a 4.9 kernel results in an error:

`setsockopt returns ENOPROTOOPT for NETLINK_EXT_ACK`

This is due to a bug in the netlink package: https://github.com/vishvananda/netlink/issues/751
which is fixed in the v1.2.1-beta.2 version commit https://github.com/vishvananda/netlink/commit/5e915e0149386ce3d02379ff93f4c0a5601779d5

**Comment by mmorel-35** [comment]
Fixed by #801
