### ISSUE TITLE
Sending DHCP requests via an alternative link

### ISSUE THREAD

**Issue by rmohr** [containernetworking/plugins#79]
I realised that the DHCP ipam plugin can only use the created device to contact the DHCP server. I am currently in a scenario, where the device itself can't reach the DHCP server. There is routing and traffic mirroring happening in-between.

I think that adding the option to talk to the DHCP server via a different device could be a nice addition, and it would fit the spec models separation between ipam and main pretty well.

What do you guys think?

**Comment by squeed** [comment]
Not a bad idea. One question: how will you handle gateway accessibility? In the typical case, dhcp is used for macvlan-style links, where the container is "directly connected." In that case, you'd want to use the gateway IP provided by the DHCP response.

If you manually set up proxy-arp, then that will also work. What's your plan for that?
