### ISSUE TITLE
Add a CNI for Windows

### ISSUE THREAD

**Issue by rakelkar** [containernetworking/plugins#80]
Creating a new issue to get feedback on whether it makes sense to add a Windows CNI in this repository vs a separate repo? Contrib guidelines ask for 3rd party plugins to live in their own repo - however one could possibly argue that a Windows plugin makes sense to round off CNI OS support? Looking for opinions.

WinCNI as it is implemented today is a single EXE that implements the CNI interface and uses the hcsshim GO wrapper to configure Windows HNS Networks and Endpoints (https://github.com/Microsoft/hcsshim).

**Comment by rakelkar** [comment]
Opened #85

**Comment by rosenhouse** [comment]
@rakelkar this is a good question.  thinking more about this, in relation to #77 and #84 I have a couple questions:

1) how many Windows CNI plugins are there today?  do you anticipate a large ecosystem (like there is today for linux CNI plugins)?
2) how much code will Windows CNI plugins share with Linux plugins?  how much code will Windows CNI plugins share with each other?

**Comment by rakelkar** [comment]
How many Windows CNI plugins are there today: 
The only CNI I am aware of is the [Azure CNI](https://github.com/Azure/azure-container-networking/tree/master/cni). I have reached out to the Windows Kernel [HNS - Host Networking Service folks](https://github.com/dineshgovindasamy) to comment as well. 

Do you anticipate a large ecosystem:
I think the number of plugins will be limited since their operations is dependent on Kernel support. It is possible in theory to write kernel drivers to emulate this stuff, but that would not be many (the Azure plugin is an example). 

My assumption is that this repository has canonical plugins for the base cases and folks are free to create 3rd party plugins in their own repos. To this end I think it makes sense to have canonical plugins for windows. My PR proposes plugins that configure HNS for the two primary modes: host-gw and vxlan, and is built in collaboration with the Windows [HNS](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking) team (who are onboard to help evolve this as HNS features evolve).  

Code sharing with Linux plugins:
I don't expect them to share any code with Linux plugins

Code sharing between Windows plugins:
I do expect them to share code. My PR includes shared code under pkg/hns to provision/de-provision HNS endpoints. Other examples of shared code is features that are agnostic of network type such as runtime port mapping.

**Comment by JMesser81** [comment]
Cloudbase Solutions (@alexpilotti) and team are also developing a Windows CNI plugin for OVN/OVS. HNS team will have our own first-party CNI plugin for 'l2bridge' network driver.

**Comment by astrieanna** [comment]
Should this issue be closed now that https://github.com/containernetworking/plugins/pull/193 is merged?

**Comment by rakelkar** [comment]
Resolved by #193
