### ISSUE TITLE
publish a reproducible test that defines how to eval. bandwidth plugin locally

### ISSUE THREAD

**Issue by jayunit100** [containernetworking/plugins#827]
We have some issues like https://github.com/containernetworking/plugins/issues/609 , where folks have documented the spikey behaviour of the bandwidth plugin.

Tabulating that into a graph, you get something like this: 

![image](https://user-images.githubusercontent.com/826111/217026322-55828ff3-1326-47bf-868f-28a63fefc27f.png)

## A small program

Lets reference some kind of reproducible, easily understandable test for this - one idea is a small go program (bandwidth_measure.go) which can run in two modes:
- serves 100MB file every time you hit it 
- continuously attempts to pull the same 100MB file

Then we can just test bandwidth inside the cluster in a predictable way without any external deps 

## A more realistic benchmark like EC2 or JMeter

It seems like most people hit the BW plugin in situations where the outside resource has infinite bandwidth but they dont wanna use too much internal bandwidth.  So something like picking an EC2 file and just pulling it down a bunch of times could be a easy reproducible test.  

If we want we can do JMeter instead if we dont wanna rely on someone elses file storage.  But JMeter would require us running a JMeter pod. 

## Just use the e2e.test library

We do have k8s e2e tests.  I dont know if we have one that excersizes bandwidth though. maybe we could write such a test... ?

**Comment by dcbw** [comment]
The unit tests create a network namespace and run a live test with bandwidth limiting inside that namespace. I think it would be definitely a good idea to get measurements of the behavior during that test, and potentially fail it if the behavior isn't what we expect. But at least get that data so we know how things behavior more reliably.

**Comment by jayunit100** [comment]
/reopen

I think we'd still.like to do this

**Comment by jayunit100** [comment]
hmmm. how do i reopen this?

**Comment by jayunit100** [comment]
I dont have time to work on this anymore , does anyone else want to take it up?  Im working on some different things nowadays.
