### ISSUE TITLE
difference between cni-v0.6.0.tar.gz and cni-plugins...v0.6.0.tar.gz

### ISSUE THREAD

**Issue by jeffmhastings** [containernetworking/plugins#83]
Is there any difference between the two binaries? What's the reasoning for having the downloads named similarly?

**Comment by squeed** [comment]
The "CNI" release basically doesn't contain anything; we split the repositories so we can release plugins more rapidly. I've suggested not even building "CNI" release tarballs.

Are you using any of the "CNI" binaries, or just the plugins?

**Comment by jeffmhastings** [comment]
Just the plugins. That makes sense, and is what I suspected. Thanks for the clarification.

**Comment by rosenhouse** [comment]
This looks resolved.
