### ISSUE TITLE
Add support for cloud sdn solution. 

### ISSUE THREAD

**Issue by martinyunify** [containernetworking/plugins#90]
Many SDN solution supports attaching multiple network interfaces to instance which is running on cloud. (e.g. aws,google cloud and so on). And I think it is a good idea to utilize this capability to allocate nic for docker container. 

In order to implement this feature, Following new plugins are needed.

a plugin which attaches a new network interface to instance and assign static ip stack for network interface.

I would like to implement this plugin. Any ideas are appreciated.

**Comment by hwchiu** [comment]
Have you used the [multus-cni] before?
You can use the **CustomResourceDefinition** Network to define any network objects and you can indicate what kind of the network you want to use in your POD yaml.

**Comment by rkamudhan** [comment]
@martinyunify , if interest tries to develop on host devices CNI -  https://github.com/containernetworking/plugins/tree/master/plugins/main/host-device . SRIOV CNI plugin works exactly in the same way for the connecting the VFs to the container.

**Comment by squeed** [comment]
I'm not sure that this repository is the right place for cloud-provider-specific plugins to live. These plugins are intended to be a "base set" that provide basic functionality.
