### ISSUE TITLE
Traffic shaping plugin

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#94]
A motivating example is the kubenet deprecation, but that certainly isn't the only use. It would be nice to have a chained plugin that allowed for some basic bandwidth limiting / traffic shaping.

This would be a new capability arg.

**Comment by squeed** [comment]
Oh, that's awesome. The other implementation I was looking at was the one in k8s, but I'm not particularly wedded to it. In fact, it doesn't support bursting, and since it doesn't use IFB, I suspect it doesn't rate same-host bandwidth (which might be OK...).

**Comment by squeed** [comment]
Also, I think @dnardo said he had a shaping plugin almost done?

**Comment by dnardo** [comment]
I do have something that has parity with the existing stuff in kubenet.  I was waiting for the GET call to be available since I need that for proper cleanup.  I'll clean it up and send it out for review.
