### ISSUE TITLE
documentation seems a bit unclear

### ISSUE THREAD

**Issue by nathanaelle** [containernetworking/plugins#958]
hi,

this part of the documentation seems unclear for https://www.cni.dev/plugins/current/main/bridge/ 
> vlan (int, optional): assign VLAN tag. Defaults to none.
> preserveDefaultVlan (boolean, optional): indicates whether the default vlan must be preserved on the veth end connected to  the bridge. Defaults to true.
> vlanTrunk (list, optional): assign VLAN trunk tag. Defaults to none.

how to :
– allow packets for/from a vlan and keep incoming tagged  aka `bridge vlan add vid x dev x` ?
– allow packets for/from a vlan and untag incoming aka `bridge vlan add vid x dev x untagged` ?
– force outgoing untagged packet to be tagged aka `bridge vlan add vid x dev x pvid` ?
– allow packets for/from a vlan and untag incoming and force outgoing untaged aka `bridge vlan add vid x dev x pvid untagged` ?

I hope you will understand my issue is not about understanding vlans or linux, but about understanding the doc for transposing a wellknown standard linux command to manage bridges and vlans to a cni configuration

**Comment by mlguerrero12** [comment]
@nathanaelle, please have a look at https://github.com/containernetworking/cni.dev/pull/134

**Comment by nathanaelle** [comment]
thank you :)
