### ISSUE TITLE
Golang 1.10 - network namespaces from within a long-lived, multithreaded Go processes

### ISSUE THREAD

**Issue by DennisDenuto** [containernetworking/plugins#98]
## Context

Golang 1.10 [changed how m-threads are spawned. They are spawned from a template thread and not cloned from the parent process.](https://github.com/hyangah/go/commit/2f4ab34983d83130f3ab5a8d34ed823b40fdeb08)

Before this change, [there was no safe way to change the namespace within a long lived multi-thread process](https://github.com/containernetworking/plugins/tree/master/pkg/ns).

## Issue
We wrote a [test](https://gist.github.com/DennisDenuto/7c75e8a41b40b95b6a94f00d4b46a62d#file-ns_linux_test-go-L97) for this to make sure the commit fixed the issue. It, correctly, eventually fails when run with golang 1.9. It passes with golang 1.10.

However, when we run the test with the `untilItFails` flag in 1.10. It will eventually error where the test failed to get the network namespace, because the process task directory was missing.

```
    Expected error:
        <*os.PathError | 0xc42319b590>: {
            Op: "open",
            Path: "/proc/29002/task/29015/ns/net",
            Err: 0x2,
        }
        open /proc/29002/task/29015/ns/net: no such file or directory
    not to have occurred

    /media/sf_dev_go/src/github.com/containernetworking/plugins/pkg/ns/ns_linux_test.go:112
```

## Steps to Reproduce

1. Run the [test](https://gist.github.com/DennisDenuto/7c75e8a41b40b95b6a94f00d4b46a62d#file-ns_linux_test-go-L97) with `untilItFails` with golang 1.10. It consistently took about 300 tries for us.
2. See it fail. 

## Expected result

We expected it to succeed indefinitely. 

## Current result

It eventually fails after running the test too many times.

## Possible Fix

We found by [adding a `runtime.UnlockOSThread()`](https://gist.github.com/DennisDenuto/c6288a9d77296787af21d5e54cbce2d6#file-ns_linux-go-L289) to the `Do` function prevents the test from failing (even when running with the `untilItFails`). 

We believe unlocking the os thread should be safe in 1.10 due to [this](https://go-review.googlesource.com/c/go/+/45752) fix.

However, this fix causes the test to slow down *significantly* over time, for reasons that we don't understand.

**Comment by squeed** [comment]
Interesting! 1.10 also adds another interesting feature, where if a G terminates on a locked M, the M is terminated instead of being returned to the free M pool. I strongly suspect that's the cause of the error message you're seeing: as you walk `/proc`, you're racing against threads (tasks) being terminated. 

So, I'm not entirely sure that it's a... bug... but everything in this shadowy corner of go and linux is unclear.

**Comment by squeed** [comment]
Also, I'd love to understand why you see slowdowns. Theoretically by unlocking, you're preserving M's, which should be faster.

**Comment by bboreham** [comment]
Note https://github.com/containernetworking/cni/issues/262
